import {Wallet} from "ethers";import {it,expect,vi} from "vitest";
vi.mock("server-only",()=>({}));
import {createCredential,rehearsalChallenge,rehearsalProof} from "./demo";
import {demoFixtureSchema} from "./demo-schema";
import {demoMessages} from "./i18n";
import {runHeuristics} from "./heuristics";
import {seedConfiguration} from "../scripts/seed-demo";
it("detects each translated synthetic CBI call as HIGH without LLM/network",()=>{for(const t of Object.values(demoMessages))expect(runHeuristics(t.transcript)).toMatchObject({risk:"HIGH",hardFlag:true});});
it("rehearsal uses actual browser-compatible credential/proof crypto: fake fails, signed officer passes",async()=>{const issuer=Wallet.createRandom(),officer=Wallet.createRandom(),fake=Wallet.createRandom();const credential=await createCredential(issuer,{officerName:"Synthetic Demo Officer",roleTitle:"Information Officer",officerAddress:officer.address,expiresAt:new Date(Date.now()+3600000).toISOString()});const challenge=rehearsalChallenge();expect((await rehearsalProof(fake,credential,challenge)).result).toBe("NOT_VERIFIED");expect((await rehearsalProof(officer,credential,challenge)).result).toBe("VERIFIED_AUTHORIZED");expect((await rehearsalProof(officer,{...credential,roleTitle:"Tampered"},challenge)).result).toBe("NOT_VERIFIED");expect((await rehearsalProof(officer,credential,{...challenge,expiresAt:new Date(0).toISOString()})).result).toBe("NOT_VERIFIED");});
it("public seed fixture rejects private keys, encrypted backups and tampered credentials",async()=>{const w=Wallet.createRandom();const c=await createCredential(w,{officerName:"Synthetic Demo Officer",roleTitle:"Information Officer",officerAddress:Wallet.createRandom().address,expiresAt:new Date(Date.now()+3600000).toISOString()});expect(demoFixtureSchema.parse({version:1,credential:c}).credential).toEqual(c);expect(()=>demoFixtureSchema.parse({version:1,credential:c,privateKey:w.privateKey})).toThrow();expect(()=>demoFixtureSchema.parse({version:1,credential:c,backup:{ciphertext:"secret"}})).toThrow();expect(()=>demoFixtureSchema.parse({version:1,credential:{...c,officerAddress:Wallet.createRandom().address}})).toThrow();});
it("seed refuses non-opted-in or production chains and requires service configuration",()=>{expect(()=>seedConfiguration({})).toThrow();const env={DEMO_SEED_ALLOWED:"1",NEXT_PUBLIC_SUPABASE_URL:"https://synthetic.supabase.co",SUPABASE_SERVICE_ROLE_KEY:"synthetic-service-key",CHAIN_ID:"31337"};expect(seedConfiguration(env).chainId).toBe(31337);expect(()=>seedConfiguration({...env,CHAIN_ID:"137"})).toThrow();expect(()=>seedConfiguration({...env,SUPABASE_SERVICE_ROLE_KEY:""})).toThrow();});

import {demoOutcomeText} from "./demo";
it("a completed result changes language without rerunning or replacing the stored verdict",()=>{const storedVerdict="VERIFIED_AUTHORIZED" as const;expect(demoOutcomeText(storedVerdict,"en")).toBe("VERIFIED + AUTHORIZED");expect(demoOutcomeText(storedVerdict,"hi")).toContain("सत्यापित");expect(demoOutcomeText(storedVerdict,"ta")).not.toBe(demoOutcomeText(storedVerdict,"en"));expect(demoOutcomeText("SIMULATION","hi")).toBe(demoMessages.hi.simulation);});
