import {PGlite} from "@electric-sql/pglite";import {readFile,readdir} from "node:fs/promises";import {resolve} from "node:path";import {beforeAll,beforeEach,afterAll,it,expect,vi} from "vitest";import {assertRole,type Identity} from "./auth-policy";import {manifestHash} from "./evidence";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({admin:vi.fn(),role:vi.fn(),anchor:vi.fn(),read:vi.fn(),status:vi.fn()}));
vi.mock("./auth",()=>({requireRole:mocks.role,authErrorResponse:(e:{status:number;code:string})=>Response.json({error:{code:e.code}},{status:e.status})}));
vi.mock("./supabase/admin",()=>({createAdminClient:mocks.admin}));
vi.mock("./chain",async original=>({...await original<typeof import("./chain")>(),anchorEvidence:mocks.anchor,evidenceAnchor:mocks.read,transactionStatus:mocks.status}));
import {POST as createRoute} from "../app/api/evidence/route";import {POST as itemsRoute} from "../app/api/evidence/[id]/items/route";import {POST as anchorRoute} from "../app/api/evidence/[id]/anchor/route";import {POST as verifyRoute} from "../app/api/evidence/verify/route";import {ChainError} from "./chain";
let db:PGlite;const alice="00000000-0000-4000-8000-000000000901",bob="00000000-0000-4000-8000-000000000902";let identity:Identity|null={id:alice,role:"citizen"};
const hash="0x"+"a".repeat(64),tx="0x"+"b".repeat(64);
const item={id:"20000000-0000-4000-8000-000000000901",kind:"transcript",sha256:hash,size:12,mime:"text/plain"};
const anchor={transactionHash:tx,timestamp:"2026-10-03T12:00:00.000Z",blockNumber:12,chainId:31337,registryAddress:"0x"+"1".repeat(40)};
class Query{
 private cols="*";private values:unknown[]=[];private filters:string[]=[];private payload:Record<string,unknown>|null=null;private updating=false;private singleRow=false;
 constructor(private table:string){}select(columns="*"){this.cols=columns;return this;}insert(value:Record<string,unknown>){this.payload=value;return this;}update(value:Record<string,unknown>){this.payload=value;this.updating=true;return this;}eq(field:string,value:unknown){this.values.push(value);this.filters.push(field+"=$"+this.values.length);return this;}single(){this.singleRow=true;return this;}
 async then(done:(value:unknown)=>unknown){try{let statement="select "+this.cols+" from public."+this.table+(this.filters.length?" where "+this.filters.join(" and "):"");
 if(this.payload){const fields=Object.keys(this.payload);const params=fields.map(f=>{const v=this.payload![f];this.values.push(v!==null&&typeof v==="object"?JSON.stringify(v):v);return "$"+this.values.length;});statement=this.updating?"update public."+this.table+" set "+fields.map((f,i)=>f+"="+params[i]).join(",")+(this.filters.length?" where "+this.filters.join(" and "):"")+" returning "+this.cols:"insert into public."+this.table+"("+fields.join(",")+") values("+params.join(",")+") returning "+this.cols;}
 const r=await db.query(statement,this.values);return done({data:this.singleRow?r.rows[0]??null:r.rows,error:null});}catch(e){return done({data:null,error:{code:(e as {code:string}).code}});}}
}
const client={from:(t:string)=>new Query(t),rpc:async(name:string,args:Record<string,unknown>)=>{try{const values=Object.values(args).map(v=>v!==null&&typeof v==="object"?JSON.stringify(v):v);const r=await db.query<{data:unknown}>("select public."+name+"("+values.map((_,i)=>"$"+(i+1)).join(",")+") as data",values);return {data:r.rows[0].data,error:null};}catch(e){return {data:null,error:{code:(e as {code:string}).code}};}}};
function req(data:unknown){return new Request("http://localhost/api/evidence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});}function context(id:string){return {params:Promise.resolve({id})};}
async function setupCase(){const r=await createRoute(req({title:"Synthetic Evidence"}));expect(r.status).toBe(201);const id=(await r.json()).case.id;expect((await itemsRoute(req({items:[item]}),context(id))).status).toBe(201);return id;}
beforeAll(async()=>{db=new PGlite();await db.exec("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;");const directory=resolve(process.cwd(),"../supabase/migrations");for(const file of(await readdir(directory)).filter(x=>x.endsWith(".sql")).sort())await db.exec(await readFile(resolve(directory,file),"utf8"));for(const id of[alice,bob])await db.query("insert into auth.users(id) values($1)",[id]);await db.exec("set role service_role");mocks.admin.mockReturnValue(client);mocks.role.mockImplementation(async roles=>({...assertRole(identity,roles),client}));},60000);
beforeEach(async()=>{await db.exec("delete from public.evidence_items;delete from public.evidence_cases;delete from public.rate_limits");identity={id:alice,role:"citizen"};vi.stubEnv("RATE_LIMIT_PEPPER","synthetic-evidence-pepper-123");mocks.read.mockReset().mockResolvedValue(null);mocks.anchor.mockReset().mockImplementation(async()=>{mocks.read.mockResolvedValue(anchor);return {transactionHash:tx,blockNumber:12};});mocks.status.mockReset().mockResolvedValue("pending");});
afterAll(async()=>{await db.close();vi.unstubAllEnvs();});
it("freezes server metadata, anchors exactly its canonical manifest, and saves the receipt",async()=>{const id=await setupCase();const response=await anchorRoute(req({}),context(id));expect(response.status).toBe(200);const value=await response.json();expect(value.manifestHash).toBe(await manifestHash(value.manifest));expect(mocks.anchor).toHaveBeenCalledWith(value.manifestHash);expect((await db.query<{status:string;onchain_tx:string}>("select status,onchain_tx from public.evidence_cases where id=$1",[id])).rows[0]).toEqual({status:"anchored",onchain_tx:tx});expect((await itemsRoute(req({items:[{...item,id:bob}]}),context(id))).status).toBe(409);expect((await anchorRoute(req({}),context(id))).status).toBe(200);expect(mocks.anchor).toHaveBeenCalledTimes(1);});
it("uses actual RLS own-row visibility and denies direct metadata mutations",async()=>{const id=await setupCase();identity={id:bob,role:"citizen"};expect((await anchorRoute(req({}),context(id))).status).toBe(409);expect(mocks.anchor).not.toHaveBeenCalled();for(const user of[alice,bob]){await db.exec("begin;set local role authenticated");try{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[user]);expect((await db.query("select * from public.evidence_cases")).rows).toHaveLength(user===alice?1:0);expect((await db.query("select * from public.evidence_items")).rows).toHaveLength(user===alice?1:0);}finally{await db.exec("rollback");}}await db.exec("begin;set local role authenticated");try{await expect(db.query("update public.evidence_cases set onchain_tx=$1",[tx])).rejects.toMatchObject({code:"42501"});}finally{await db.exec("rollback");}});
it("persists uncertain transaction hashes and never resends a pending anchor",async()=>{const id=await setupCase();mocks.anchor.mockRejectedValueOnce(new ChainError("TRANSACTION_PENDING",tx));expect((await anchorRoute(req({}),context(id))).status).toBe(503);expect((await anchorRoute(req({}),context(id))).status).toBe(409);expect(mocks.anchor).toHaveBeenCalledTimes(1);mocks.read.mockResolvedValue(anchor);expect((await anchorRoute(req({}),context(id))).status).toBe(200);expect(mocks.anchor).toHaveBeenCalledTimes(1);});
it("rejects raw-content payloads and unauthenticated writes",async()=>{expect((await createRoute(req({title:"Synthetic",text:"raw"}))).status).toBe(400);const id=await setupCase();expect((await itemsRoute(req({items:[{...item,content:"raw text"}]}),context(id))).status).toBe(400);identity=null;expect((await createRoute(req({title:"Synthetic"}))).status).toBe(401);});
it("checks the chain independently of a supplied timestamp and fails closed on unavailable RPC",async()=>{const m={version:1,caseId:alice,items:[item]};expect(await(await verifyRoute(req(m))).json()).toMatchObject({anchor:null,manifestHash:await manifestHash(m)});mocks.read.mockResolvedValue(anchor);expect(await(await verifyRoute(req(m))).json()).toMatchObject({anchor});mocks.read.mockRejectedValue(new ChainError("RPC_UNAVAILABLE"));expect((await verifyRoute(req(m))).status).toBe(503);});
