import "server-only";
import {BlockList,isIP} from "node:net";
import {lookup} from "node:dns/promises";
import {request as httpsRequest} from "node:https";
import type {GuardianPayload} from "./guardian-schema";
const blocked=new BlockList();for(const [address,prefix] of [["0.0.0.0",8],["10.0.0.0",8],["100.64.0.0",10],["127.0.0.0",8],["169.254.0.0",16],["172.16.0.0",12],["192.0.0.0",24],["192.0.2.0",24],["192.168.0.0",16],["192.88.99.0",24],["198.18.0.0",15],["198.51.100.0",24],["203.0.113.0",24],["224.0.0.0",4],["240.0.0.0",4]] as const)blocked.addSubnet(address,prefix,"ipv4");
const publicV6=new BlockList();publicV6.addSubnet("2000::",3,"ipv6");const blockedV6=new BlockList();for(const[address,prefix]of[["2001::",23],["2001:db8::",32],["2002::",16]]as const)blockedV6.addSubnet(address,prefix,"ipv6");
export function isPublicAddress(address:string){const family=isIP(address);return family===4?!blocked.check(address,"ipv4"):family===6?publicV6.check(address,"ipv6")&&!blockedV6.check(address,"ipv6"):false;}
export function webhookURL(value:string){const url=new URL(value);const host=url.hostname.replace(/^\[|\]$/g,"").toLowerCase();if(url.protocol!=="https:"||url.username||url.password||url.hash||(url.port&&url.port!=="443")||host==="localhost"||/\.(?:local|localhost|internal)$/.test(host)||(isIP(host)&&!isPublicAddress(host)))throw new Error("UNSAFE_TARGET");return url;}
export async function resolveWebhook(value:string){const url=webhookURL(value);const host=url.hostname.replace(/^\[|\]$/g,"");let timer:ReturnType<typeof setTimeout>|undefined;try{const addresses=isIP(host)?[{address:host,family:isIP(host)}]:await Promise.race([lookup(host,{all:true,verbatim:true}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error("DELIVERY_FAILED")),4000);})]);if(!addresses.length||addresses.some(item=>!isPublicAddress(item.address)))throw new Error("UNSAFE_TARGET");return {url,address:addresses[0].address,family:addresses[0].family};}finally{if(timer)clearTimeout(timer);}}
async function postPinned(target:string,data:unknown,headers:Record<string,string>){const resolved=await resolveWebhook(target);return new Promise<{status:number;body:string}>((resolve,reject)=>{const bytes=Buffer.from(JSON.stringify(data));let settled=false;const finish=(error?:Error,value?:{status:number;body:string})=>{if(settled)return;settled=true;clearTimeout(timer);if(error)reject(new Error("DELIVERY_FAILED"));else resolve(value!);};const req=httpsRequest(resolved.url,{method:"POST",agent:false,headers:{"Content-Type":"application/json","Content-Length":String(bytes.length),...headers},lookup:(_host,options,callback)=>{if(options.all)(callback as unknown as (error:null,addresses:{address:string;family:number}[])=>void)(null,[{address:resolved.address,family:resolved.family}]);else callback(null,resolved.address,resolved.family);}},res=>{const chunks:Buffer[]=[];let size=0;res.on("data",chunk=>{size+=chunk.length;if(size>8192){req.destroy();finish(new Error());}else chunks.push(Buffer.from(chunk));});res.on("end",()=>finish(undefined,{status:res.statusCode??0,body:Buffer.concat(chunks).toString("utf8")}));res.on("error",()=>finish(new Error()));});const timer=setTimeout(()=>{req.destroy();finish(new Error());},4000);req.on("error",()=>finish(new Error()));req.end(bytes);});}
export async function deliverGuardian(contact:{channel:"webhook"|"telegram";target:string;webhook_secret?:string|null},payload:GuardianPayload,alertId:string){
 try{if(contact.channel==="webhook"){const headers:Record<string,string>={"Idempotency-Key":alertId};if(contact.webhook_secret)headers.Authorization="Bearer "+contact.webhook_secret;const response=await postPinned(contact.target,payload,headers);return response.status>=200&&response.status<300;}
 const token=process.env.TELEGRAM_BOT_TOKEN;if(!token||!/^\d+:[A-Za-z0-9_-]{20,200}$/.test(token)||!/^-[1-9]\d{0,18}$|^[1-9]\d{0,18}$/.test(contact.target))return false;
 const response=await postPinned("https://api.telegram.org/bot"+token+"/sendMessage",{chat_id:contact.target,text:JSON.stringify(payload),disable_web_page_preview:true},{});if(response.status<200||response.status>=300)return false;return JSON.parse(response.body).ok===true;
 }catch{return false;}
}
