import {PGlite} from "@electric-sql/pglite";import {readFile,readdir} from "node:fs/promises";import {resolve} from "node:path";import {beforeAll,beforeEach,afterAll,expect,it,vi} from "vitest";import {assertRole,type Identity} from "./auth-policy";
vi.mock("server-only",()=>({}));const mock=vi.hoisted(()=>({admin:vi.fn(),role:vi.fn(),optional:vi.fn(),deliver:vi.fn()}));vi.mock("./auth",()=>({requireRole:mock.role,authErrorResponse:(e:{status:number;code:string})=>Response.json({error:{code:e.code}},{status:e.status})}));vi.mock("./supabase/admin",()=>({createAdminClient:mock.admin}));vi.mock("./optional-auth",()=>({optionalIdentity:mock.optional}));vi.mock("./guardian-delivery",async original=>({...await original<typeof import("./guardian-delivery")>(),deliverGuardian:mock.deliver}));
import {GET as contacts,POST as add} from "../app/api/guardians/route";import {DELETE as remove} from "../app/api/guardians/[id]/route";import {GET as history,POST as alert} from "../app/api/alerts/route";import {POST as analyze} from "../app/api/analyze/route";
let db:PGlite;const alice="00000000-0000-4000-8000-000000000c01",bob="00000000-0000-4000-8000-000000000c02";let identity:Identity|null={id:alice,role:"citizen"};
class Query{
 private cols="*";private values:unknown[]=[];private filters:string[]=[];private payload:Record<string,unknown>|null=null;private action:"read"|"insert"|"update"|"delete"="read";private one=false;private orderBy="";private rowLimit="";
 constructor(private table:string){}select(cols="*"){this.cols=cols;return this;}insert(value:Record<string,unknown>){this.payload=value;this.action="insert";return this;}update(value:Record<string,unknown>){this.payload=value;this.action="update";return this;}delete(){this.action="delete";return this;}eq(field:string,value:unknown){this.values.push(value);this.filters.push(field+"=$"+this.values.length);return this;}is(field:string,_value:null){void _value;this.filters.push(field+" is null");return this;}gte(field:string,value:unknown){this.values.push(value);this.filters.push(field+">=$"+this.values.length);return this;}single(){this.one=true;return this;}maybeSingle(){this.one=true;return this;}order(field:string,options:{ascending:boolean}){this.orderBy=" order by "+field+(options.ascending?" asc":" desc");return this;}limit(n:number){this.rowLimit=" limit "+n;return this;}
 async then(done:(value:unknown)=>unknown){try{let sql="select "+this.cols+" from public."+this.table+(this.filters.length?" where "+this.filters.join(" and "):"")+this.orderBy+this.rowLimit;if(this.payload){const fields=Object.keys(this.payload);const params=fields.map(f=>{let v=this.payload![f];if(f==="tactics"&&Array.isArray(v))v="{"+v.join(",")+"}";else if(v!==null&&typeof v==="object")v=JSON.stringify(v);this.values.push(v);return "$"+this.values.length;});sql=this.action==="update"?"update public."+this.table+" set "+fields.map((f,i)=>f+"="+params[i]).join(",")+(this.filters.length?" where "+this.filters.join(" and "):"")+" returning "+this.cols:"insert into public."+this.table+"("+fields.join(",")+") values("+params.join(",")+") returning "+this.cols;}if(this.action==="delete")sql="delete from public."+this.table+(this.filters.length?" where "+this.filters.join(" and "):"")+" returning "+this.cols;const result=await db.query(sql,this.values);return done({data:this.one?result.rows[0]??null:result.rows,error:null});}catch(e){return done({data:null,error:{code:(e as {code:string}).code}});}}
}
const client={from:(t:string)=>new Query(t),rpc:async(name:string,args:Record<string,unknown>)=>{try{const values=Object.values(args).map(v=>v!==null&&typeof v==="object"?JSON.stringify(v):v);const result=await db.query<{data:unknown}>("select public."+name+"("+values.map((_,i)=>"$"+(i+1)).join(",")+") as data",values);return {data:result.rows[0].data,error:null};}catch(e){return {data:null,error:{code:(e as {code:string}).code}};}}};
// Authenticated Supabase client is independently filtered to its owner by real RLS in the policy test.
const request=(data:unknown)=>new Request("http://localhost/api/guardian",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
const contact={name:"Synthetic family",channel:"webhook",target:"https://family.example.invalid/hook",secret:"synthetic-contact-secret",consent:true};
const input={eventKey:"00000000-0000-4000-8000-000000000c10",riskScore:95,tactics:["DIGITAL_ARREST"]};
beforeAll(async()=>{db=new PGlite();await db.exec("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;");const dir=resolve(process.cwd(),"../supabase/migrations");for(const file of(await readdir(dir)).filter(x=>x.endsWith(".sql")).sort())await db.exec(await readFile(resolve(dir,file),"utf8"));for(const id of[alice,bob])await db.query("insert into auth.users(id) values($1)",[id]);await db.exec("set role service_role");mock.admin.mockReturnValue(client);mock.role.mockImplementation(async roles=>({...assertRole(identity,roles),client}));},60000);
beforeEach(async()=>{await db.exec("delete from public.alerts;delete from public.guardians;delete from public.analyses;delete from public.rate_limits");identity={id:alice,role:"citizen"};vi.stubEnv("RATE_LIMIT_PEPPER","synthetic-guardian-rate-pepper");vi.stubEnv("LLM_PROVIDER","mock");mock.deliver.mockReset().mockResolvedValue(true);mock.optional.mockReset().mockImplementation(async()=>identity);});afterAll(async()=>{await db.close();vi.unstubAllEnvs();vi.restoreAllMocks();});
it("logs and delivers a metadata-only HIGH alert once per event/contact including concurrent retries",async()=>{expect((await add(request(contact))).status).toBe(201);const responses=await Promise.all([alert(request(input)),alert(request(input))]);expect(responses.map(r=>r.status)).toEqual([200,200]);expect(mock.deliver).toHaveBeenCalledOnce();const payload=mock.deliver.mock.calls[0][1];expect(Object.keys(payload)).toEqual(["riskScore","tactics","summary","time"]);const rows=(await db.query<{payload:unknown;status:string}>("select payload,status from public.alerts")).rows;expect(rows).toHaveLength(1);expect(rows[0].status).toBe("sent");expect(JSON.stringify(rows)).not.toContain("family.example.invalid");expect(JSON.stringify(rows)).not.toContain("synthetic-contact-secret");});
it("triggers Guardian for cached and uncached authenticated analyzer HIGH results without raw transcripts",async()=>{await add(request(contact));const data={text:"Synthetic digital arrest; contact synthetic@example.invalid",consent:true,eventKey:input.eventKey};const first=await analyze(request(data));expect(first.status).toBe(200);expect(await first.json()).toMatchObject({result:{risk:"HIGH"},guardian:{alerts:[{status:"sent"}]}});expect(await(await analyze(request(data))).json()).toMatchObject({cached:true});expect(mock.deliver).toHaveBeenCalledOnce();const all=(await db.query("select payload from public.alerts")).rows;expect(JSON.stringify(all)).not.toContain("synthetic@example.invalid");expect(JSON.stringify(all)).not.toContain("Synthetic digital arrest;");expect((await db.query("select input_text from public.analyses")).rows).toEqual([{input_text:null}]);});
it("marks simulation and logs failed delivery honestly",async()=>{await add(request(contact));mock.deliver.mockResolvedValue(false);const r=await alert(request({...input,simulate:true}));expect(await r.json()).toMatchObject({alerts:[{status:"failed"}]});const row=(await db.query<{payload:{summary:string};event_source:string;sent_at:null}>("select payload,event_source,sent_at from public.alerts")).rows[0];expect(row.event_source).toBe("simulation");expect(row.payload.summary).toContain("SIMULATION");expect(row.sent_at).toBeNull();await alert(request({...input,simulate:true}));expect(mock.deliver).toHaveBeenCalledOnce();});
it("requires login and rejects private endpoints, raw text, forged summaries, low score and excess contacts",async()=>{identity=null;expect((await add(request(contact))).status).toBe(401);expect((await alert(request(input))).status).toBe(401);identity={id:alice,role:"citizen"};for(const target of["http://family.example.invalid","https://127.0.0.1","https://169.254.169.254"])expect((await add(request({...contact,target}))).status).toBe(400);for(const value of [{...input,text:"raw"},{...input,summary:"raw"},{...input,riskScore:20}])expect((await alert(request(value))).status).toBe(400);for(let i=0;i<3;i++)expect((await add(request({...contact,name:"Synthetic contact "+i}))).status).toBe(201);expect((await add(request(contact))).status).toBe(409);});
it("prevents deleting another user's contact and hides bearer secrets in API responses",async()=>{const created=await(await add(request(contact))).json();expect(created.guardian).not.toHaveProperty("webhook_secret");identity={id:bob,role:"citizen"};expect((await remove(request({}),{params:Promise.resolve({id:created.guardian.id})})).status).toBe(404);identity={id:alice,role:"citizen"};expect(JSON.stringify(await(await contacts()).json())).not.toContain("synthetic-contact-secret");expect((await remove(request({}),{params:Promise.resolve({id:created.guardian.id})})).status).toBe(200);});
it("enforces own-row RLS, read-only contact access and secret-column restrictions",async()=>{await add(request(contact));await alert(request(input));for(const actor of[alice,bob]){await db.exec("begin;set local role authenticated");try{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[actor]);for(const table of["guardians","alerts"])expect((await db.query("select id from public."+table)).rows).toHaveLength(actor===alice?1:0);}finally{await db.exec("rollback");}}for(const sql of["select webhook_secret from public.guardians","delete from public.guardians","update public.guardians set target='https://127.0.0.1'"]){await db.exec("begin;set local role authenticated");try{await expect(db.exec(sql)).rejects.toMatchObject({code:"42501"});}finally{await db.exec("rollback");}}});
it("rate limits alert requests and returns empty delivery list for no contacts",async()=>{expect(await(await alert(request(input))).json()).toEqual({alerts:[]});for(let n=1;n<20;n++)expect((await alert(request(input))).status).toBe(200);expect((await alert(request(input))).status).toBe(429);});
it("returns alert history without exposing target URL or contact secrets",async()=>{await add(request(contact));await alert(request(input));const data=await(await history()).json();expect(data.alerts).toHaveLength(1);expect(JSON.stringify(data)).not.toContain("family.example.invalid");expect(JSON.stringify(data)).not.toContain("synthetic-contact-secret");});
