import {beforeAll,expect,it} from "vitest";import {Wallet} from "ethers";import {pressureDecision} from "./pressure";import {runHeuristics} from "./heuristics";import type {LookupResult} from "./registry-client";import type {Challenge,Verdict} from "./verification-schema";import {factsHash,receiptMessage} from "./verdict-receipt";
const signer=Wallet.createRandom(),now=Date.parse("2026-10-04T00:00:00Z");const challenge:Challenge={id:"00000000-0000-4000-8000-000000000b01",code:"000000",claimedEntity:"Synthetic office",claimedCategory:"government",expiresAt:new Date(now+120000).toISOString(),purpose:"information",amount:"0.00",payee:""};
const lookup:LookupResult={count:0,distinctReporterCount:0,eligibleReporterCount:0,anchoredCount:0,pendingCount:0,risk:"unreported",minAccountAgeSeconds:86400,chainCount:"0",countsMatch:true};let verdict:Verdict;
beforeAll(async()=>{const facts={challengeId:challenge.id,eventId:"00000000-0000-4000-8000-000000000b02",actionId:"00000000-0000-4000-8000-000000000b03",officerId:"00000000-0000-4000-8000-000000000b04",purpose:"information",amount:"0.00",payee:"",result:"VERIFIED_AUTHORIZED" as const,reason:"ACTION_AUTHORIZED",issuedAt:new Date(now).toISOString(),authorizedUntil:new Date(now+60000).toISOString()};const hash=factsHash(facts);verdict={result:"VERIFIED_AUTHORIZED",reason:"ACTION_AUTHORIZED",eventId:facts.eventId,receipt:{version:1,facts,factsHash:hash,signer:signer.address,signature:await signer.signMessage(receiptMessage(hash))}};});
const input=()=>({lookup,analysis:runHeuristics("Synthetic office appointment tomorrow"),official:true,challenge,verdict,expectedSigner:signer.address,now});
it("requires a pinned, bound, fresh authorized receipt to show safe to proceed",()=>{expect(pressureDecision(input())).toEqual({action:"VERIFIED_SAFE",reason:"authorized"});expect(pressureDecision({...input(),expectedSigner:Wallet.createRandom().address}).action).toBe("HANG_UP");expect(pressureDecision({...input(),challenge:{...challenge,id:"00000000-0000-4000-8000-000000000b09"}}).action).toBe("HANG_UP");});
it("never lets identity-only, missing checks or LOW risk prove safety",()=>{expect(pressureDecision({...input(),verdict:{...verdict,result:"IDENTITY_VERIFIED_NOT_AUTHORIZED"}}).action).toBe("DO_NOT_PAY");expect(pressureDecision({...input(),verdict:null}).action).toBe("HANG_UP");expect(pressureDecision({...input(),lookup:null}).action).toBe("DO_NOT_PAY");expect(pressureDecision({...input(),official:false}).action).toBe("DO_NOT_PAY");});
it("hard flags and registry warnings override even a valid official authorization",()=>{expect(pressureDecision({...input(),analysis:runHeuristics("Digital arrest. Transfer to a safe account")})).toMatchObject({action:"HANG_UP",reason:"strongSignals"});expect(pressureDecision({...input(),lookup:{...lookup,count:1,risk:"reported"}})).toMatchObject({action:"DO_NOT_PAY",reason:"reported"});expect(pressureDecision({...input(),lookup:{...lookup,count:3,risk:"high"}}).action).toBe("HANG_UP");});
it("expires the proceed card at action expiry or snapshot expiry and rejects receipt tampering",()=>{expect(pressureDecision({...input(),now:now+60001}).action).toBe("HANG_UP");expect(pressureDecision({...input(),now:now+120001}).action).toBe("HANG_UP");for(const facts of [{...verdict.receipt.facts,payee:"synthetic@bank"},{...verdict.receipt.facts,authorizedUntil:new Date(now+999999).toISOString()}])expect(pressureDecision({...input(),verdict:{...verdict,receipt:{...verdict.receipt,facts}}}).action).toBe("HANG_UP");});

it("does not greenlight unresolved MEDIUM analyzer risk",()=>expect(pressureDecision({...input(),analysis:runHeuristics("Please pay urgently")})).toEqual({action:"DO_NOT_PAY",reason:"uncertainSignals"}));
