import {PGlite} from "@electric-sql/pglite";
import {readFile,readdir} from "node:fs/promises";import {resolve} from "node:path";
import {beforeAll,beforeEach,afterAll,expect,it,vi} from "vitest";
import {Contract,ContractFactory,JsonRpcProvider,Wallet,parseEther} from "ethers";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({admin:vi.fn(),role:vi.fn(),write:vi.fn(),read:vi.fn(),count:vi.fn(),status:vi.fn(),context:vi.fn(),real:process.env.RUN_REGISTRY_CHAIN_INTEGRATION==="1"}));
vi.mock("./supabase/admin",()=>({createAdminClient:mocks.admin}));vi.mock("./auth",()=>({requireRole:mocks.role,authErrorResponse:(e:{status:number;code:string})=>Response.json({error:{code:e.code}},{status:e.status})}));
vi.mock("./chain",async original=>{const actual=await original<typeof import("./chain")>();return {...actual,reportScam:(...args:Parameters<typeof actual.reportScam>)=>mocks.real?actual.reportScam(...args):mocks.write(...args),reportAnchor:(key:string)=>mocks.real?actual.reportAnchor(key):mocks.read(key),relayedReportCount:(hash:string)=>mocks.real?actual.relayedReportCount(hash):mocks.count(hash),transactionStatus:(tx:string)=>mocks.real?actual.transactionStatus(tx):mocks.status(tx),registryContext:()=>mocks.real?actual.registryContext():mocks.context()};});
import {POST as report,GET as recent} from "../app/api/report/route";import {GET as lookup} from "../app/api/lookup/route";import {POST as retry} from "../app/api/report/[id]/anchor/route";
import {assertRole,type Identity} from "./auth-policy";import {idHash} from "./identifier-hash";import {ChainError,reportCount} from "./chain";
let db:PGlite,provider:JsonRpcProvider|undefined,realContract:Contract|undefined;const actors=["00000000-0000-4000-8000-000000000a01","00000000-0000-4000-8000-000000000a02","00000000-0000-4000-8000-000000000a03","00000000-0000-4000-8000-000000000a04"];let identity:Identity|null={id:actors[0],role:"citizen"};
const anchors=new Map<string,{idHash:string;transactionHash:string;blockNumber:number}>();const counts=new Map<string,number>();
class Query{
 private fields="*";private values:unknown[]=[];private filters:string[]=[];private payload:Record<string,unknown>|null=null;private change=false;private one=false;private ordering="";private rowLimit="";
 constructor(private table:string){}select(fields="*"){this.fields=fields;return this;}insert(value:Record<string,unknown>){this.payload=value;return this;}update(value:Record<string,unknown>){this.payload=value;this.change=true;return this;}eq(field:string,value:unknown){this.values.push(value);this.filters.push(field+"=$"+this.values.length);return this;}single(){this.one=true;return this;}order(field:string,options:{ascending:boolean}){this.ordering=" order by "+field+(options.ascending?" asc":" desc");return this;}limit(n:number){this.rowLimit=" limit "+n;return this;}
 async then(done:(value:unknown)=>unknown){try{let sql="select "+this.fields+" from public."+this.table+(this.filters.length?" where "+this.filters.join(" and "):"")+this.ordering+this.rowLimit;if(this.payload){const fields=Object.keys(this.payload);const params=fields.map(f=>{this.values.push(this.payload![f]);return "$"+this.values.length;});sql=this.change?"update public."+this.table+" set "+fields.map((f,i)=>f+"="+params[i]).join(",")+(this.filters.length?" where "+this.filters.join(" and "):"")+" returning "+this.fields:"insert into public."+this.table+"("+fields.join(",")+") values("+params.join(",")+") returning "+this.fields;}const result=await db.query(sql,this.values);return done({data:this.one?result.rows[0]??null:result.rows,error:null});}catch(e){return done({data:null,error:{code:(e as {code:string}).code}});}}
}
const client={from:(t:string)=>new Query(t),rpc:async(name:string,args:Record<string,unknown>)=>{try{const values=Object.values(args);const r=await db.query<{data:unknown}>("select public."+name+"("+values.map((_,i)=>"$"+(i+1)).join(",")+") as data",values);return {data:r.rows[0].data,error:null};}catch(e){return {data:null,error:{code:(e as {code:string}).code}};}}};
const request=(data:unknown)=>new Request("http://localhost/api/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
const input={value:"synthetic@bank",type:"upi",category:"impersonation",acknowledge:true};
const look=(value=input.value)=>lookup(new Request("http://localhost/api/lookup?"+new URLSearchParams({value})));
const retryReport=(id:string)=>retry(request({}),{params:Promise.resolve({id})});
beforeAll(async()=>{
 db=new PGlite();await db.exec("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;");const directory=resolve(process.cwd(),"../supabase/migrations");for(const file of(await readdir(directory)).filter(x=>x.endsWith(".sql")).sort())await db.exec(await readFile(resolve(directory,file),"utf8"));for(const id of actors)await db.query("insert into auth.users(id) values($1)",[id]);await db.exec("set role service_role");mocks.admin.mockReturnValue(client);mocks.role.mockImplementation(async roles=>({...assertRole(identity,roles),client}));
 if(mocks.real){provider=new JsonRpcProvider("http://127.0.0.1:8545",undefined,{cacheTimeout:-1});expect((await provider.getNetwork()).chainId).toBe(BigInt(31337));const artifact=JSON.parse(await readFile(resolve(process.cwd(),"../contracts/artifacts/contracts/TrustRegistry.sol/TrustRegistry.json"),"utf8"));const wallet=Wallet.createRandom().connect(provider);await(await(await provider.getSigner(0)).sendTransaction({to:wallet.address,value:parseEther("1")})).wait();const deployed=await new ContractFactory(artifact.abi,artifact.bytecode,wallet).deploy();await deployed.waitForDeployment();realContract=new Contract(await deployed.getAddress(),artifact.abi,provider);vi.stubEnv("RPC_URL","http://127.0.0.1:8545");vi.stubEnv("CHAIN_ID","31337");vi.stubEnv("REGISTRY_ADDRESS",await deployed.getAddress());vi.stubEnv("RELAYER_PRIVATE_KEY",wallet.privateKey);}
},60000);
beforeEach(async()=>{await db.exec("delete from public.scam_reports;delete from public.rate_limits;update public.profiles set created_at=clock_timestamp()-interval '2 days'");await db.query("update public.profiles set created_at=clock_timestamp() where id=$1",[actors[3]]);identity={id:actors[0],role:"citizen"};vi.stubEnv("REGISTRY_PEPPER","synthetic-pepper-registry-test");vi.stubEnv("RATE_LIMIT_PEPPER","synthetic-pepper-rate-test");vi.stubEnv("REGISTRY_MIN_ACCOUNT_AGE_SECONDS","86400");anchors.clear();counts.clear();mocks.context.mockReset().mockResolvedValue({chainId:31337,registryAddress:"0x"+"1".repeat(40)});mocks.status.mockReset().mockResolvedValue("pending");mocks.read.mockReset().mockImplementation(async key=>anchors.get(key)??null);mocks.count.mockReset().mockImplementation(async hash=>String(counts.get(hash)??0));mocks.write.mockReset().mockImplementation(async(hash,key)=>{if(!anchors.has(key)){const tx="0x"+String(anchors.size+1).padStart(64,"0");anchors.set(key,{idHash:hash,transactionHash:tx,blockNumber:anchors.size+1});counts.set(hash,(counts.get(hash)??0)+1);}return anchors.get(key);});});
afterAll(async()=>{await db?.close();provider?.destroy();vi.unstubAllEnvs();vi.restoreAllMocks();});
it("rejects a normalized duplicate and keeps database and chain counts equal for distinct users",async()=>{for(const actor of actors.slice(0,3)){identity={id:actor,role:"citizen"};const r=await report(request(input));expect(r.status).toBe(201);expect(await r.json()).toMatchObject({report:{anchorStatus:"anchored"}});}identity={id:actors[0],role:"citizen"};expect((await report(request({...input,value:" SYNTHETIC@BANK "}))).status).toBe(409);const result=await(await look()).json();expect(result).toMatchObject({count:3,distinctReporterCount:3,eligibleReporterCount:3,anchoredCount:3,chainCount:"3",countsMatch:true,risk:"high"});const rows=(await db.query("select * from public.scam_reports")).rows;expect(JSON.stringify(rows)).not.toContain("synthetic@bank");expect(JSON.stringify(rows)).not.toContain("synthetic-pepper");if(mocks.real){expect(await realContract!.reportCount(idHash(input.value))).toBe(BigInt(3));expect(await reportCount(idHash(input.value))).toBe("3");}else expect(mocks.write).toHaveBeenCalledTimes(3);},60000);
if(!mocks.real){
 it("counts young-account allegations but excludes them from high until the minimum age is met",async()=>{for(const actor of [actors[0],actors[1],actors[3]]){identity={id:actor,role:"citizen"};expect((await report(request(input))).status).toBe(201);}expect(await(await look()).json()).toMatchObject({count:3,distinctReporterCount:3,eligibleReporterCount:2,risk:"reported"});vi.stubEnv("REGISTRY_MIN_ACCOUNT_AGE_SECONDS","0");expect(await(await look()).json()).toMatchObject({eligibleReporterCount:3,risk:"high"});});
 it("rejects anonymous reporting, unvalidated input and enforces per-user rate limits",async()=>{identity=null;expect((await report(request(input))).status).toBe(401);identity={id:actors[0],role:"citizen"};expect((await report(request({...input,category:"synthetic@bank"}))).status).toBe(400);expect((await report(request({...input,value:"bad"}))).status).toBe(400);for(let n=0;n<18;n++)expect((await report(request({...input,value:"synthetic"+n+"@bank"}))).status).toBe(201);expect((await report(request({...input,value:"synthetic-last@bank"}))).status).toBe(429);});
 it("persists a failed anchor, reconciles mined-but-unrecorded writes and does not increment twice",async()=>{mocks.write.mockImplementationOnce(async(hash,key)=>{anchors.set(key,{idHash:hash,transactionHash:"0x"+"a".repeat(64),blockNumber:1});counts.set(hash,1);throw new ChainError("TRANSACTION_PENDING","0x"+"a".repeat(64));});const first=await report(request(input));expect(first.status).toBe(201);const id=(await first.json()).report.id;expect((await retryReport(id)).status).toBe(200);expect(mocks.write).toHaveBeenCalledOnce();expect(await(await look()).json()).toMatchObject({count:1,chainCount:"1",countsMatch:true});mocks.write.mockRejectedValueOnce(new ChainError("RPC_UNAVAILABLE"));const second=await report(request({...input,value:"synthetic-two@bank"}));expect(second.status).toBe(202);const pendingId=(await second.json()).report.id;expect((await retryReport(pendingId)).status).toBe(200);expect((await retryReport(pendingId)).status).toBe(200);expect(await(await look("synthetic-two@bank")).json()).toMatchObject({anchoredCount:1,chainCount:"1",countsMatch:true});});
 it("does not rebroadcast an uncertain transaction and enforces retry ownership",async()=>{mocks.write.mockRejectedValueOnce(new ChainError("TRANSACTION_PENDING","0x"+"b".repeat(64)));const response=await report(request(input));expect(response.status).toBe(202);const id=(await response.json()).report.id;expect((await retryReport(id)).status).toBe(409);expect(mocks.write).toHaveBeenCalledOnce();identity={id:actors[1],role:"citizen"};expect((await retryReport(id)).status).toBe(409);const r=await(await recent(new Request("http://localhost/api/report?mine=true"))).json();expect(r.reports).toEqual([]);});
 it("keeps aggregate reads anonymous and prevents direct authenticated tampering or deletion",async()=>{await report(request(input));identity=null;expect((await look()).status).toBe(200);const publicRows=(await(await recent(new Request("http://localhost/api/report"))).json()).reports;expect(publicRows).toHaveLength(1);expect(publicRows[0]).not.toHaveProperty("reporter_id");expect(publicRows[0]).not.toHaveProperty("id_hash");for(const actor of actors.slice(0,2)){await db.exec("begin;set local role authenticated");try{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[actor]);expect((await db.query("select * from public.scam_reports")).rows).toHaveLength(actor===actors[0]?1:0);}finally{await db.exec("rollback");}}for(const sql of ["delete from public.scam_reports","update public.scam_reports set category='other'","insert into public.scam_reports(reporter_id,id_hash,id_type,category) values('"+actors[0]+"','0x"+"a".repeat(64)+"','upi','other')"]){await db.exec("begin;set local role authenticated");try{await expect(db.exec(sql)).rejects.toMatchObject({code:"42501"});}finally{await db.exec("rollback");}}});
 it("rate limits public lookups and reports chain outages without hiding DB allegations",async()=>{await report(request(input));mocks.count.mockRejectedValue(new ChainError("RPC_UNAVAILABLE"));expect(await(await look()).json()).toMatchObject({count:1,risk:"reported",chainCount:null,countsMatch:null});for(let n=1;n<20;n++)expect((await look()).status).toBe(200);expect((await look()).status).toBe(429);});
 it("atomically rejects concurrent retries while an anchor lease is active",async()=>{
  let ready!:()=>void,release!:()=>void;const entered=new Promise<void>(resolve=>{ready=resolve;});const barrier=new Promise<void>(resolve=>{release=resolve;});
  mocks.write.mockImplementationOnce(async(hash,key)=>{ready();await barrier;const tx="0x"+"c".repeat(64);anchors.set(key,{idHash:hash,transactionHash:tx,blockNumber:1});counts.set(hash,1);return anchors.get(key);});
  const first=report(request(input));await entered;
  const row=(await db.query<{id:string}>("select id from public.scam_reports")).rows[0];
  try{expect((await retryReport(row.id)).status).toBe(409);expect((await report(request(input))).status).toBe(409);}finally{release();}
  expect((await first).status).toBe(201);expect(mocks.write).toHaveBeenCalledOnce();expect(await(await look()).json()).toMatchObject({count:1,chainCount:"1",countsMatch:true});
 });

}

