import {PGlite} from "@electric-sql/pglite";import {readFile,readdir} from "node:fs/promises";import {resolve} from "node:path";import {beforeAll,beforeEach,afterEach,afterAll,it,expect,vi} from "vitest";import {assertRole,type Identity} from "./auth-policy";import {payeeHash} from "./registry";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({admin:vi.fn(),role:vi.fn(),optional:vi.fn()}));
vi.mock("./auth",()=>({requireRole:mocks.role,authErrorResponse:(e:{status:number;code:string})=>Response.json({error:{code:e.code}},{status:e.status})}));
vi.mock("./supabase/admin",()=>({createAdminClient:mocks.admin}));
vi.mock("./optional-auth",()=>({optionalIdentity:mocks.optional}));
import {POST as guardRoute} from "../app/api/upi-guard/route";import {POST as choiceRoute} from "../app/api/upi-guard/choice/route";import {POST as analyzeRoute} from "../app/api/analyze/route";
let db:PGlite;const alice="00000000-0000-4000-8000-000000000901",bob="00000000-0000-4000-8000-000000000902";let identity:Identity|null={id:alice,role:"citizen"};
class Query{
 is(field:string,value:null){this.filters.push(field+" is "+(value===null?"null":"not null"));return this;}
 private counting=false;private head=false;private ordering="";private rowLimit:number|null=null;
 order(field:string,options:{ascending:boolean}){this.ordering=" order by "+field+(options.ascending?" asc":" desc");return this;}
 limit(n:number){this.rowLimit=n;return this;}maybeSingle(){this.singleRow=true;return this;}
 gte(field:string,value:unknown){this.values.push(value);this.filters.push(field+">=$"+this.values.length);return this;}

 private cols="*";private values:unknown[]=[];private filters:string[]=[];private payload:Record<string,unknown>|null=null;private updating=false;private singleRow=false;
 constructor(private table:string){}select(columns="*",options?:{count?:string;head?:boolean}){this.cols=columns;this.counting=Boolean(options?.count);this.head=Boolean(options?.head);return this;}insert(value:Record<string,unknown>){this.payload=value;return this;}update(value:Record<string,unknown>){this.payload=value;this.updating=true;return this;}eq(field:string,value:unknown){this.values.push(value);this.filters.push(field+"=$"+this.values.length);return this;}single(){this.singleRow=true;return this;}
 async then(done:(value:unknown)=>unknown){try{let statement="select "+this.cols+" from public."+this.table+(this.filters.length?" where "+this.filters.join(" and "):"");
 if(this.payload){const fields=Object.keys(this.payload);const params=fields.map(f=>{const v=this.payload![f];this.values.push(f==="tactics"&&Array.isArray(v)?"{"+v.join(",")+"}":v!==null&&typeof v==="object"?JSON.stringify(v):v);return "$"+this.values.length;});statement=this.updating?"update public."+this.table+" set "+fields.map((f,i)=>f+"="+params[i]).join(",")+(this.filters.length?" where "+this.filters.join(" and "):"")+" returning "+this.cols:"insert into public."+this.table+"("+fields.join(",")+") values("+params.join(",")+") returning "+this.cols;}
 if(!this.payload)statement+=this.ordering+(this.rowLimit===null?"":" limit "+this.rowLimit);const r=await db.query(statement,this.values);return done({count:this.counting?r.rows.length:null,data:this.head?null:this.singleRow?r.rows[0]??null:r.rows,error:null});}catch(e){return done({data:null,error:{code:(e as {code:string}).code}});}}
}
const client={from:(t:string)=>new Query(t),rpc:async(name:string,args:Record<string,unknown>)=>{try{const values=Object.values(args).map(v=>v!==null&&typeof v==="object"?JSON.stringify(v):v);const r=await db.query<{data:unknown}>("select public."+name+"("+values.map((_,i)=>"$"+(i+1)).join(",")+") as data",values);return {data:r.rows[0].data,error:null};}catch(e){return {data:null,error:{code:(e as {code:string}).code}};}}};
function req(data:unknown){return new Request("http://localhost/api/evidence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});}
async function begin(overrides:Record<string,string>={}){const r=await guardRoute(req({payee:"synthetic@bank",amount:"1",latestRisk:"LOW",...overrides}));expect(r.status).toBe(201);return r.json();}
async function choose(session:{id:string;token:string},choice:string){return choiceRoute(req({sessionId:session.id,token:session.token,choice}));}
beforeAll(async()=>{db=new PGlite();await db.exec("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;");const directory=resolve(process.cwd(),"../supabase/migrations");for(const file of(await readdir(directory)).filter(x=>x.endsWith(".sql")).sort())await db.exec(await readFile(resolve(directory,file),"utf8"));for(const id of[alice,bob])await db.query("insert into auth.users(id) values($1)",[id]);await db.exec("set role service_role");mocks.admin.mockReturnValue(client);mocks.role.mockImplementation(async roles=>({...assertRole(identity,roles),client}));},60000);
beforeEach(async()=>{await db.exec("delete from public.upi_guard_choices;delete from public.alerts;delete from public.upi_guard_sessions;delete from public.analyses;delete from public.scam_reports;delete from public.rate_limits");identity={id:alice,role:"citizen"};vi.stubEnv("RATE_LIMIT_PEPPER","synthetic-pepper-rate-limit");vi.stubEnv("REGISTRY_PEPPER","synthetic-pepper-registry");vi.stubEnv("UPI_GUARD_THRESHOLD","10000");vi.stubEnv("GUARDIAN_WEBHOOK_URL","");vi.stubEnv("LLM_PROVIDER","mock");mocks.optional.mockReset().mockResolvedValue(null);vi.unstubAllGlobals();});
// Keep each rate-limit test in one minute bucket, even during a slow full-suite run.
let restoreClock:()=>void;
beforeEach(()=>{const clock=vi.spyOn(Date,"now").mockReturnValue(Date.now());restoreClock=()=>clock.mockRestore();});
afterEach(()=>{restoreClock();});
afterAll(async()=>{await db.close();vi.unstubAllEnvs();vi.unstubAllGlobals();});

it("holds high amounts for sixty seconds, alerts immediately, and logs cancellation once",async()=>{const d=await begin({amount:"10000"});expect(d.session.reasons).toEqual(["AMOUNT"]);expect(Date.parse(d.session.coolingUntil)-Date.parse(d.session.serverNow)).toBeGreaterThan(59000);expect(d.alert).toMatchObject({status:"sent",mode:"in_app"});expect((await choose(d.session,"continue")).status).toBe(409);expect((await choose(d.session,"cancel")).status).toBe(200);expect((await choose(d.session,"cancel")).status).toBe(200);expect((await choose(d.session,"continue")).status).toBe(409);expect((await db.query("select * from public.upi_guard_choices")).rows).toHaveLength(1);});
it("independently triggers on registry reports and latest HIGH risk",async()=>{await db.query("insert into public.scam_reports(reporter_id,id_hash,id_type,category) values($1,$2,'upi','Synthetic')",[alice,payeeHash("synthetic@bank")]);expect((await begin({amount:"1"})).session.reasons).toEqual(["REGISTRY"]);await db.exec("delete from public.scam_reports");expect((await begin({amount:"1",latestRisk:"HIGH"})).session.reasons).toEqual(["ANALYZER"]);expect((await db.query("select * from public.alerts")).rows).toHaveLength(2);});
it("continues only after elapsed server time and never moves real money",async()=>{const d=await begin({amount:"12000"});await db.query("update public.upi_guard_sessions set cooling_until=clock_timestamp()-interval '1 second' where id=$1",[d.session.id]);const r=await choose(d.session,"continue");expect(r.status).toBe(200);expect(await r.json()).toMatchObject({choice:"continue",demo:true});const clear=await begin({amount:"1"});expect(clear.alert).toBeNull();expect(clear.session.reasons).toEqual([]);expect((await choose(clear.session,"continue")).status).toBe(200);});
it("requires bearer proof, account ownership, and unexpired session",async()=>{mocks.optional.mockResolvedValue({id:alice,role:"citizen"});const d=await begin({amount:"1"});expect((await choose({...d.session,token:"0".repeat(64)},"cancel")).status).toBe(409);mocks.optional.mockResolvedValue({id:bob,role:"citizen"});expect((await choose(d.session,"cancel")).status).toBe(409);mocks.optional.mockResolvedValue({id:alice,role:"citizen"});await db.query("update public.upi_guard_sessions set expires_at=clock_timestamp()-interval '1 second' where id=$1",[d.session.id]);expect((await choose(d.session,"cancel")).status).toBe(409);});
it("stores peppered payee/token hashes without raw identifiers and enforces own-row RLS",async()=>{mocks.optional.mockResolvedValue({id:alice,role:"citizen"});const d=await begin({amount:"10000"});await choose(d.session,"cancel");const rows=(await db.query("select * from public.upi_guard_sessions")).rows;expect(JSON.stringify(rows)).not.toContain("synthetic@bank");expect(JSON.stringify(rows)).not.toContain(d.session.token);for(const user of[alice,bob]){await db.exec("begin;set local role authenticated");try{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[user]);for(const table of["upi_guard_sessions","upi_guard_choices","alerts"])expect((await db.query("select * from public."+table)).rows).toHaveLength(user===alice?1:0);}finally{await db.exec("rollback");}}await db.exec("begin;set local role authenticated");try{await expect(db.query("update public.upi_guard_sessions set cooling_until=now()")).rejects.toMatchObject({code:"42501"});}finally{await db.exec("rollback");}});
it("reports webhook failure honestly and sends no payee, transcript or bearer token",async()=>{vi.stubEnv("GUARDIAN_WEBHOOK_URL","https://guardian.example.test/demo");const fetch=vi.fn(async(url:unknown,options:RequestInit)=>{void url;void options;throw new Error("secret-url");});vi.stubGlobal("fetch",fetch);const d=await begin({amount:"10000"});expect(d.alert).toMatchObject({status:"failed",mode:"webhook"});const payload=JSON.parse(fetch.mock.calls[0][1].body as string);expect(payload).toMatchObject({demo:true,event:"upi_cooling_off"});expect(JSON.stringify(payload)).not.toContain("synthetic@bank");expect(JSON.stringify(payload)).not.toContain(d.session.token);});
it("redacts optional AI, caches by normalized hash, and never persists raw text",async()=>{const data={text:"Please pay urgently to synthetic@bank",consent:true};const first=await analyzeRoute(req(data));expect(first.status).toBe(200);expect(await first.json()).toMatchObject({cached:false,result:{provider:"heuristics"}});const second=await analyzeRoute(req(data));expect(await second.json()).toMatchObject({cached:true});const row=(await db.query<{input_text:string|null;input_hash:string}>("select input_text,input_hash from public.analyses")).rows[0];expect(row.input_text).toBeNull();expect(row.input_hash).toMatch(/^[0-9a-f]{64}$/);expect((await analyzeRoute(req({text:"Synthetic",consent:false}))).status).toBe(400);});
it("rate limits database-backed demo creation and rejects unvalidated inputs",async()=>{expect((await guardRoute(req({payee:"bad",amount:"1",latestRisk:"LOW"}))).status).toBe(400);for(let n=0;n<20;n++)expect((await guardRoute(req({payee:"synthetic@bank",amount:"1",latestRisk:"LOW"}))).status).toBe(201);expect((await guardRoute(req({payee:"synthetic@bank",amount:"1",latestRisk:"LOW"}))).status).toBe(429);});

it("analyzer API redacts paid-provider input and persists metadata-only hybrid cache",async()=>{vi.stubEnv("LLM_PROVIDER","openai");vi.stubEnv("LLM_API_KEY","synthetic-key");vi.stubEnv("LLM_MODEL","synthetic-model");const fetch=vi.fn(async(url:unknown,options:RequestInit)=>{void url;void options;return Response.json({choices:[{message:{content:JSON.stringify({score:0,tactics:[]})}}]});});vi.stubGlobal("fetch",fetch);const data={text:"अभी digital arrest; contact synthetic@example.invalid +91 00000 00000",consent:true,language:"hi"};const first=await analyzeRoute(req(data));expect(first.status).toBe(200);expect(await first.json()).toMatchObject({cached:false,result:{provider:"hybrid",hardFlag:true,risk:"HIGH"}});const sent=JSON.stringify(fetch.mock.calls[0]);expect(sent).not.toContain("00000");expect(sent).not.toContain("synthetic@example.invalid");expect(sent).toContain("BEGIN_UNTRUSTED_TRANSCRIPT");expect(await(await analyzeRoute(req(data))).json()).toMatchObject({cached:true,result:{provider:"hybrid"}});expect(fetch).toHaveBeenCalledOnce();const saved=(await db.query("select input_text from public.analyses")).rows;expect(saved).toEqual([{input_text:null}]);});
it("analyzer API excludes profile-owned poisoned cache and rate limits anonymous requests",async()=>{const text="Synthetic appointment tomorrow";const {analysisHash}=await import("./analyzer");await db.query("insert into public.analyses(user_id,input_hash,risk_score,verdict,tactics,provider,latency_ms,input_text) values($1,$2,100,'HIGH','{}','heuristics',0,'synthetic private text')",[alice,analysisHash(text)]);const response=await analyzeRoute(req({text,consent:true}));expect(await response.json()).toMatchObject({cached:false,result:{risk:"LOW"}});for(let n=1;n<20;n++)expect((await analyzeRoute(req({text,consent:true}))).status).toBe(200);expect((await analyzeRoute(req({text,consent:true}))).status).toBe(429);expect((await analyzeRoute(req({text,consent:true,language:"unsupported"}))).status).toBe(429);expect((await analyzeRoute(req({text:"   ",consent:true}))).status).toBe(429);});

