"use client";
import {useEffect,useMemo,useRef,useState} from "react";import Link from "next/link";import {runHeuristics,resultSchema,type AnalysisResult} from "../../lib/heuristics";import {rememberAnalysis} from "../../lib/analyzer-state";import {pressureMessages,assistMessages,commonMessages,analyzerMessages,analyzerLanguageNames,type Locale} from "../../lib/i18n";import {useLanguage} from "./language";import {buttonClass,fieldClass} from "./key-panel";
export function highlightSegments(text:string,spans:NonNullable<AnalysisResult["highlights"]>){const parts:{text:string;mark:boolean}[]=[];let offset=0;for(const span of [...spans].sort((a,b)=>a.start-b.start||b.end-a.end)){if(span.start<offset||span.end>text.length||span.end<=span.start)continue;if(span.start>offset)parts.push({text:text.slice(offset,span.start),mark:false});parts.push({text:text.slice(span.start,span.end),mark:true});offset=span.end;}if(offset<text.length)parts.push({text:text.slice(offset),mark:false});return parts;}
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((event:{resultIndex:number;results:ArrayLike<{isFinal:boolean;0:{transcript:string}}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null;start():void;stop():void;abort():void};
type Constructor=new()=>Recognition;
export function AnalyzerPanel({live=false}:{live?:boolean}){const{locale,setLocale}=useLanguage();const t=assistMessages[locale];const copy=analyzerMessages[locale];const[text,setText]=useState("");const[active,setActive]=useState(false);const[remote,setRemote]=useState<AnalysisResult|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[consent,setConsent]=useState(false);const[guardianConsent,setGuardianConsent]=useState(false);const[guardianStatus,setGuardianStatus]=useState("");const guardianEvent=useRef<string|null>(null),guardianSent=useRef<string|null>(null),guardianRequest=useRef<AbortController|null>(null);const[speechConsent,setSpeechConsent]=useState(false);const[listening,setListening]=useState(false);const recognition=useRef<Recognition|null>(null);const request=useRef<AbortController|null>(null);
 const local=useMemo(()=>text.trim()?runHeuristics(text):null,[text]);const result=active?(remote??local):null;
 useEffect(()=>{if(result)rememberAnalysis(result);},[result]);useEffect(()=>()=>{request.current?.abort();recognition.current?.abort();guardianRequest.current?.abort();},[]);
 function change(value:string){guardianRequest.current?.abort();guardianEvent.current=null;guardianSent.current=null;setGuardianStatus("");request.current?.abort();setBusy(false);setText(value.slice(0,10000));setRemote(null);setActive(live);}
 async function ai(){if(!text.trim()||!consent)return;if(guardianConsent)guardianEvent.current??=crypto.randomUUID();recognition.current?.stop();setBusy(true);setError("");setActive(true);const controller=new AbortController();request.current?.abort();request.current=controller;try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,consent:true,language:locale,notifyGuardian:guardianConsent,...(guardianEvent.current?{eventKey:guardianEvent.current}:{})}),signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error?.code);if(!controller.signal.aborted)setRemote(resultSchema.parse(d.result));}catch(e){if(!controller.signal.aborted){setRemote(null);setError(e instanceof Error?e.message:"SERVICE_UNAVAILABLE");}}finally{if(!controller.signal.aborted)setBusy(false);}}
 useEffect(()=>{if(!guardianConsent||result?.risk!=="HIGH")return;guardianEvent.current??=crypto.randomUUID();if(guardianSent.current===guardianEvent.current)return;guardianSent.current=guardianEvent.current;const controller=new AbortController();guardianRequest.current?.abort();guardianRequest.current=controller;fetch("/api/alerts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventKey:guardianEvent.current,riskScore:result.score,tactics:result.tactics,language:locale}),signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error();if(!controller.signal.aborted)setGuardianStatus(!data.alerts?.length?"none":data.alerts.some((x:{status:string})=>x.status!=="sent")?"failed":"sent");}).catch(()=>{if(!controller.signal.aborted)setGuardianStatus("failed");});},[guardianConsent,result,locale]);
 function dictate(){if(!speechConsent)return;setError("");const surface=window as Window&{SpeechRecognition?:Constructor;webkitSpeechRecognition?:Constructor};const Speech=surface.SpeechRecognition??surface.webkitSpeechRecognition;if(!Speech){setError("SPEECH_UNAVAILABLE");return;}recognition.current?.abort();const session=new Speech();recognition.current=session;session.lang=locale==="hi"?"hi-IN":locale==="ta"?"ta-IN":"en-IN";session.continuous=true;session.interimResults=false;session.onresult=event=>{let final="";for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)final+=" "+event.results[i][0].transcript;if(final){guardianRequest.current?.abort();guardianEvent.current=null;guardianSent.current=null;setGuardianStatus("");request.current?.abort();setBusy(false);setText(v=>(v+final).slice(0,10000));setRemote(null);setActive(true);}};session.onerror=()=>{setError("SPEECH_FAILED");setListening(false);};session.onend=()=>setListening(false);try{session.start();setListening(true);}catch{setError("SPEECH_FAILED");}}
 return <main className="mx-auto max-w-3xl space-y-6 px-5 py-10 text-xl"><h1 className="text-4xl font-bold">{live?t.live:t.analyze}</h1><label className="block">{copy.language}<select className={fieldClass} value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{(["en","hi","ta"] as const).map(language=><option key={language} value={language}>{analyzerLanguageNames[language]}</option>)}</select></label><p className="rounded border-2 border-teal-900 p-4">{t.localPrivacy}</p>{live&&<p>{t.noCall}</p>}<label className="block">{t.text}<textarea rows={8} className={fieldClass} maxLength={10000} value={text} disabled={busy} onChange={e=>change(e.target.value)}/></label><button className={buttonClass} disabled={!text.trim()||busy} onClick={()=>{setRemote(null);setActive(true);setError("");}}>{t.rules}</button>
 {live&&<section className="space-y-3 rounded border-2 border-amber-800 p-4"><h2 className="text-2xl font-bold">{t.dictate}</h2><p>{t.speechWarning}</p><label className="block"><input type="checkbox" checked={speechConsent} onChange={e=>{setSpeechConsent(e.target.checked);if(!e.target.checked)recognition.current?.stop();}}/> {t.speechConsent}</label><button className={buttonClass} disabled={!speechConsent||listening||busy} onClick={dictate}>{t.start}</button><button className={buttonClass} disabled={!listening} onClick={()=>recognition.current?.stop()}>{t.stop}</button>{listening&&<p role="status">{t.listening}</p>}<a href="https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition" target="_blank" rel="noreferrer" className="underline">{t.speechSource}</a></section>}
 <section className="space-y-3 border-t pt-4"><p>{t.aiPrivacy}</p><label className="block"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> {t.aiConsent}</label><button className={buttonClass} disabled={!consent||!text.trim()||busy} onClick={ai}>{t.ai}</button></section>
 <label className="block"><input type="checkbox" checked={guardianConsent} onChange={e=>setGuardianConsent(e.target.checked)}/> {pressureMessages[locale].guardian}</label>{guardianStatus&&<p role="status">{guardianStatus==="sent"?pressureMessages[locale].guardianSent:guardianStatus==="none"?pressureMessages[locale].guardianNone:pressureMessages[locale].guardianFailure} <Link className="underline" href="/guardian">{t.guardian}</Link></p>}
 {busy&&<p role="status">{t.pending}</p>}{error&&<p role="alert">{t.errors[error]??t.error}</p>}
 {result&&<section role="status" className={"space-y-3 rounded border-4 p-5 "+(result.risk==="HIGH"?"border-red-800 bg-red-50":result.risk==="MEDIUM"?"border-amber-800 bg-amber-50":"border-teal-800 bg-teal-50")}><h2 className="text-4xl font-extrabold">{t.risks[result.risk]}</h2><p>{t.score}: {result.score}/100</p><meter aria-label={copy.gauge} min={0} max={100} low={20} high={70} optimum={0} value={result.score} className="h-8 w-full">{result.score}/100</meter><p className="inline-block rounded border-2 px-3 py-1 font-bold" data-mode={result.provider}>{t.providers[result.provider]} · {result.latencyMs} {commonMessages[locale].milliseconds}</p><h3 className="text-2xl font-bold">{copy.explanation}</h3><p>{copy.summary[result.risk]}</p><ul>{result.tactics.map(x=><li key={x}>{t.tactics[x]}</li>)}</ul><h3 className="text-2xl font-bold">{copy.phrases}</h3>{!result.tactics.length&&<p>{copy.noSignals}</p>}<p className="whitespace-pre-wrap break-words">{highlightSegments(text,result.highlights??local?.highlights??[]).map((segment,index)=>segment.mark?<mark key={index} className="bg-yellow-200 font-bold text-black">{segment.text}</mark>:<span key={index}>{segment.text}</span>)}</p><h3 className="text-2xl font-bold">{copy.recommendation}</h3><p>{copy.actions[result.risk]}</p><p>{t.notProof}</p><button className={buttonClass} onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="satyacall-analyzer-result.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{t.export}</button></section>}
 <div className="flex flex-wrap gap-5"><Link className="underline" href={live?"/analyze":"/live-assist"}>{live?t.analyze:t.live}</Link><Link className="underline" href="/upi-guard">{t.upi}</Link></div></main>;
}

