"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {createKeyVault,createCredential,type Credential} from "../../lib/crypto";
import {runHeuristics,type AnalysisResult} from "../../lib/heuristics";
import {rehearsalChallenge,rehearsalProof,demoOutcomeText,type DemoOutcome} from "../../lib/demo";
import {demoConfigSchema,demoFixtureSchema,demoIds,demoInstitutionName,demoNumber,type DemoConfig} from "../../lib/demo-schema";
import {challengeSchema,createVerificationToken,verdictSchema,type Verdict} from "../../lib/verification-schema";
import {verifyVerdictReceipt} from "../../lib/verdict-receipt";
import {publicReportSchema,txExplorerUrl} from "../../lib/registry-client";
import {demoBackupMessages,demoMessages,assistMessages,guardianMessages} from "../../lib/i18n";
import {useLanguage} from "./language";
import {buttonClass,fieldClass,downloadJson,type BrowserWallet} from "./key-panel";
export function DemoPanel(){
 const{locale}=useLanguage(),t=demoMessages[locale];
 const[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState<"failed"|"login"|"noGuardian"|"alertPending"|"pending"|null>(null),[connected,setConnected]=useState(false),[config,setConfig]=useState<DemoConfig|null>(null);
 const[passphrase,setPassphrase]=useState(""),[ready,setReady]=useState(false),[analysis,setAnalysis]=useState<AnalysisResult|null>(null),[outcome,setOutcome]=useState<DemoOutcome|null>(null),[receipt,setReceipt]=useState<Verdict["receipt"]|null>(null),[tx,setTx]=useState<{hash:string;chainId:number|null}|null>(null),[complete,setComplete]=useState(false);
 const[started,setStarted]=useState<number|null>(null),[elapsed,setElapsed]=useState(0);
 const issuerVault=useMemo(()=>createKeyVault("demo:issuer"),[]),officerVault=useMemo(()=>createKeyVault("demo:officer"),[]);
 const wallet=useRef<BrowserWallet|null>(null),credential=useRef<Credential|null>(null),eventKey=useRef<string|null>(null),reportId=useRef<string|null>(null),inFlight=useRef(false);
 useEffect(()=>{if(started===null||complete)return;const id=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(id);},[started,complete]);
 useEffect(()=>()=>{issuerVault.lock();officerVault.lock();wallet.current=null;credential.current=null;},[issuerVault,officerVault]);
 async function request(url:string,data?:unknown){const r=await fetch(url,{method:data===undefined?"GET":"POST",cache:"no-store",...(data===undefined?{}:{headers:{"Content-Type":"application/json"},body:JSON.stringify(data)})});const d=await r.json();if(!r.ok)throw new Error(d.error?.code??"SERVICE_UNAVAILABLE");return d;}
 async function prepare(){setBusy(true);setError(null);try{let issuer:BrowserWallet;if(issuerVault.address())issuer=await issuerVault.unlock(passphrase);else{issuer=issuerVault.generateKey();await issuerVault.encryptAndStore(passphrase);}let officer:BrowserWallet;if(officerVault.address())officer=await officerVault.unlock(passphrase);else{officer=officerVault.generateKey();await officerVault.encryptAndStore(passphrase);}const c=await createCredential(issuer,{officerName:"Synthetic Demo Officer",roleTitle:"Information Officer",officerAddress:officer.address,expiresAt:new Date(Date.now()+30*86400000).toISOString()});const fixture=demoFixtureSchema.parse({version:1,credential:c});downloadJson("satyacall-demo-public.json",JSON.stringify(fixture,null,2));wallet.current=officer;credential.current=c;setReady(true);}catch{setError("failed");}finally{issuerVault.lock();setBusy(false);}}
 async function connect(){setBusy(true);setError(null);try{const data=demoConfigSchema.parse(await request("/api/demo"));const officer=await officerVault.unlock(passphrase);if(officer.address!==data.officer.wallet_address||officer.address!==data.officer.credential.officerAddress)throw new Error();wallet.current=officer;credential.current=data.officer.credential;setConfig(data);setConnected(true);setReady(true);}catch{setError("login");}finally{setBusy(false);}}
 async function ensureRehearsalKeys(){if(wallet.current&&credential.current)return;const issuer=createKeyVault("demo:temporary-issuer").generateKey();const officer=createKeyVault("demo:temporary-officer").generateKey();wallet.current=officer;credential.current=await createCredential(issuer,{officerName:"Synthetic Demo Officer",roleTitle:"Information Officer",officerAddress:officer.address,expiresAt:new Date(Date.now()+3600000).toISOString()});}
 async function run(target:number){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError(null);setOutcome(null);setReceipt(null);try{
 if(started===null)setStarted(Date.now());
 if(target===1){const a=runHeuristics(t.transcript);if(a.risk!=="HIGH")throw new Error();setAnalysis(a);}
 if(target===2){const a=analysis;if(!a)throw new Error();if(connected){eventKey.current??=crypto.randomUUID();const d=await request("/api/alerts",{eventKey:eventKey.current,riskScore:a.score,tactics:a.tactics,simulate:true,language:locale});if(!d.alerts.length)throw new Error("NO_CONTACTS");if(d.alerts.some((x:{status:string})=>x.status!=="sent"))throw new Error("ALERT_PENDING");setOutcome("ALERT_SENT");}else setOutcome("SIMULATION");}
 if(target===3){if(connected){const d=await request("/api/challenge",{claimedEntity:demoInstitutionName,claimedCategory:"police",purpose:"payment",amount:"50000.00",payee:"synthetic-scam@invalid"});const c=challengeSchema.parse(d.challenge);const v=verdictSchema.parse(await request("/api/verify",{challengeId:c.id,token:"invalid-demo-token"}));if(v.result!=="NOT_VERIFIED"||!verifyVerdictReceipt(v.receipt,process.env.NEXT_PUBLIC_VERDICT_SIGNER_ADDRESS??""))throw new Error();setReceipt(v.receipt);setOutcome("NOT_VERIFIED");}else{await ensureRehearsalKeys();const c=rehearsalChallenge();const fake=createKeyVault("demo:fake-caller").generateKey();const proof=await rehearsalProof(fake,credential.current!,c);if(proof.result!=="NOT_VERIFIED")throw new Error();setOutcome("NOT_VERIFIED");}}
 if(target===4){if(connected){if(!config||!wallet.current)throw new Error();const d=await request("/api/challenge",{claimedEntity:config.institution.name,claimedCategory:"police",purpose:"information",amount:"0.00",payee:""});const c=challengeSchema.parse(d.challenge);const token=await createVerificationToken(wallet.current,c,config.action.id);const v=verdictSchema.parse(await request("/api/verify",{challengeId:c.id,token}));if(v.result!=="VERIFIED_AUTHORIZED"||!verifyVerdictReceipt(v.receipt,process.env.NEXT_PUBLIC_VERDICT_SIGNER_ADDRESS??"")||v.receipt.facts.challengeId!==c.id||v.receipt.facts.actionId!==config.action.id||v.receipt.facts.eventId!==v.eventId||v.receipt.facts.officerId!==config.officer.id||v.receipt.facts.result!==v.result||v.receipt.facts.purpose!==c.purpose||v.receipt.facts.amount!==c.amount||v.receipt.facts.payee!==c.payee||Date.parse(v.receipt.facts.authorizedUntil??"")<=Date.now())throw new Error();setReceipt(v.receipt);setOutcome("VERIFIED_AUTHORIZED");}else{await ensureRehearsalKeys();const proof=await rehearsalProof(wallet.current!,credential.current!,rehearsalChallenge());if(proof.result!=="VERIFIED_AUTHORIZED")throw new Error();setOutcome("VERIFIED_AUTHORIZED");}}
 if(target===5){if(connected){let report;if(reportId.current){report=(await request("/api/report/"+reportId.current+"/anchor",{})).report;}else{try{report=(await request("/api/report",{value:demoNumber,type:"phone",category:"impersonation",acknowledge:true})).report;}catch(e){if(!(e instanceof Error)||e.message!=="DUPLICATE_REPORT")throw e;const rows=(await request("/api/report?mine=true")).reports.map((r:unknown)=>publicReportSchema.parse(r));const prior=rows.find((r:{id:string})=>r.id===demoIds.report);if(!prior)throw e;reportId.current=prior.id;report=(await request("/api/report/"+prior.id+"/anchor",{})).report;}}reportId.current=report.id;if(report.anchorStatus!=="anchored"||!/^0x[0-9a-fA-F]{64}$/.test(report.anchoredTx??""))throw new Error("ANCHOR_PENDING");setTx({hash:report.anchoredTx,chainId:report.chainId??null});setOutcome("ANCHORED");}else setOutcome("SIMULATION");setComplete(true);}
 setStep(target);
 }catch(e){const code=e instanceof Error?e.message:"";setError(code==="NO_CONTACTS"?"noGuardian":code==="ALERT_PENDING"?"alertPending":code==="ANCHOR_PENDING"?"pending":"failed");}finally{inFlight.current=false;setBusy(false);}}
 function reset(){setStep(0);setAnalysis(null);setOutcome(null);setReceipt(null);setComplete(false);setTx(null);setError(null);setElapsed(0);setStarted(null);eventKey.current=null;reportId.current=null;}
 return <main className="mx-auto max-w-3xl space-y-6 px-5 py-10 text-xl"><h1 className="text-4xl font-extrabold">{t.title}</h1><p className="font-bold">{t.badge} · {connected?t.connected:t.rehearsal}</p><p>{t.intro}</p><p>{t.elapsed}: {elapsed}</p><progress max={6} value={complete?6:step+1} aria-label={t.title} className="h-6 w-full"/>
 <ol className="space-y-2">{t.steps.map((s,i)=><li key={i} aria-current={step===i?"step":undefined} className={step===i?"font-extrabold":""}>{i+1}. {s}</li>)}</ol>
 <section className="space-y-5 rounded-xl border-4 border-slate-700 bg-white p-6" aria-live="polite"><h2 className="text-3xl font-bold">{t.steps[step]}</h2><p>{t.details[step]}</p>{step===0&&<blockquote className="rounded bg-slate-100 p-4">{t.transcript}</blockquote>}{step===1&&analysis&&<><p className="text-4xl font-bold text-red-900">{assistMessages[locale].risks[analysis.risk]} · {analysis.score}/100</p><ul>{analysis.tactics.map(x=><li key={x}>{assistMessages[locale].tactics[x]}</li>)}</ul></>}{outcome&&<p className="text-3xl font-extrabold">{demoOutcomeText(outcome,locale)}</p>}{!connected&&step>0&&<p>{t.simulation}</p>}{receipt&&<details><summary>{t.receipt}</summary><pre className="overflow-x-auto whitespace-pre-wrap break-all text-sm">{JSON.stringify(receipt,null,2)}</pre></details>}{tx&&<p className="break-all">{txExplorerUrl(tx.hash,tx.chainId)?<a className="underline" href={txExplorerUrl(tx.hash,tx.chainId)!} target="_blank" rel="noreferrer">{tx.hash}</a>:tx.hash}</p>}{complete&&<p className="font-bold">{t.complete}</p>}</section>
 {error&&<p role="alert">{error==="login"?t.failed+" "+t.login:t[error]}</p>}<div className="flex flex-wrap gap-4">{!complete&&<button className={buttonClass} disabled={busy} onClick={()=>void run(step+1)}>{busy?guardianMessages[locale].busy:error?t.retry:t.next}</button>}<button className={buttonClass} disabled={busy} onClick={reset}>{t.restart}</button></div><p>{t.reportWarning}</p><Link className="block underline" href="/guardian">{t.guardian}</Link><Link className="block underline" href="/dashboard">{t.dashboard}</Link>
 {step===0&&<details className="space-y-4 rounded border p-4"><summary>{t.setup}</summary><p>{t.keysNote}</p><label className="block">{t.passphrase}<input type="password" autoComplete="off" minLength={12} maxLength={256} value={passphrase} onChange={e=>setPassphrase(e.target.value)} className={fieldClass}/></label><button className={buttonClass} disabled={busy||passphrase.length<12||connected} onClick={()=>void prepare()}>{t.prepare}</button><button className={buttonClass} disabled={busy||passphrase.length<12||connected} onClick={()=>void connect()}>{t.useConnected}</button>{ready&&<><p role="status">{t.ready}</p><button className={buttonClass} disabled={busy} onClick={()=>downloadJson("demo-institution-encrypted.json",issuerVault.exportBackup())}>{demoBackupMessages[locale].issuer}</button><button className={buttonClass} disabled={busy} onClick={()=>downloadJson("demo-officer-encrypted.json",officerVault.exportBackup())}>{demoBackupMessages[locale].officer}</button></>}</details>}
 </main>;
}




