"use client";
import {useCallback,useEffect,useState} from "react";import Link from "next/link";
import {evidenceKinds,hashFile,manifestHash,type EvidenceItem,type EvidenceManifest} from "../../lib/evidence";
import {complaintDraft,type AnchorInfo} from "../../lib/complaint";import {vaultMessages} from "../../lib/i18n";import {useLanguage} from "./language";import {buttonClass,fieldClass} from "./key-panel";
type Case={id:string;title:string;status:"draft"|"anchoring"|"anchored";manifest:EvidenceManifest|null;manifest_hash:string|null;onchain_tx:string|null;anchored_at:string|null;block_number:number|null;chain_id:number|null;registry_address:string|null};
type Item=EvidenceItem&{case_id:string};
function download(value:Blob,name:string){const url=URL.createObjectURL(value);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function EvidenceVault(){const{locale}=useLanguage();const t=vaultMessages[locale];const[cases,setCases]=useState<Case[]>([]);const[items,setItems]=useState<Item[]>([]);const[selected,setSelected]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[draft,setDraft]=useState("");const[local,setLocal]=useState<Record<string,Blob>>({});
 const load=useCallback(async()=>{const r=await fetch("/api/evidence",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error?.code);return d as {cases:Case[];items:Item[]};},[]);
 useEffect(()=>{let live=true;void load().then(d=>{if(live){setCases(d.cases);setItems(d.items);}}).catch(()=>{if(live)setError("SERVICE_UNAVAILABLE");});return()=>{live=false;};},[load]);
 const current=cases.find(c=>c.id===selected);const ownItems=items.filter(x=>x.case_id===selected);
 async function run(operation:()=>Promise<void>){setBusy(true);setError("");try{await operation();}catch(e){setError(e instanceof Error?e.message:"SERVICE_UNAVAILABLE");}finally{try{const d=await load();setCases(d.cases);setItems(d.items);}catch{setError(v=>v||"SERVICE_UNAVAILABLE");}setBusy(false);}}
 async function send(url:string,data:unknown){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error?.code??"SERVICE_UNAVAILABLE");return d;}
 async function add(files:Blob[],kind:typeof evidenceKinds[number]){if(!current||files.length===0)return;await run(async()=>{if(files.length>20)throw new Error("INVALID_INPUT");const metadata:EvidenceItem[]=[];const originals:Record<string,Blob>={};for(const file of files){const id=crypto.randomUUID();metadata.push({id,kind,sha256:await hashFile(file),size:file.size,mime:file.type.replace(/;.*$/,"")});originals[id]=file;}await send("/api/evidence/"+current.id+"/items",{items:metadata});setLocal(v=>({...v,...originals}));setDraft("");});}
 function manifest():EvidenceManifest{return current?.manifest??{version:1,caseId:selected,items:ownItems.map(({id,kind,sha256,size,mime})=>({id,kind,sha256,size,mime}))};}
 function anchorInfo():AnchorInfo|null{return current?.status==="anchored"&&current.anchored_at&&current.onchain_tx&&current.chain_id&&current.registry_address?{timestamp:current.anchored_at,transactionHash:current.onchain_tx,chainId:current.chain_id,registryAddress:current.registry_address,blockNumber:current.block_number??0}:null;}
 return <main className="mx-auto max-w-4xl space-y-6 px-5 py-10 text-xl"><div className="space-y-5 print:hidden"><h1 className="text-4xl font-bold">{t.heading}</h1><p className="rounded border-2 border-amber-800 p-4">{t.privacy}</p><Link className="underline" href="/evidence/verify">{t.verify}</Link>
 <form onSubmit={e=>{e.preventDefault();const title=new FormData(e.currentTarget).get("title");void run(async()=>{const d=await send("/api/evidence",{title});setSelected(d.case.id);setDraft("");});}}><label>{t.title}<input name="title" required maxLength={120} className={fieldClass}/></label><button disabled={busy} className={buttonClass}>{t.create}</button></form>
 <label className="block">{t.select}<select className={fieldClass} disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setDraft("");}}><option value="">—</option>{cases.map(c=><option value={c.id} key={c.id}>{c.title} · {t.states[c.status]}</option>)}</select></label>
 {error&&<p role="alert">{t.errors[error]??t.error}</p>}{busy&&<p role="status">{t.pending}</p>}
 {current&&<section className="space-y-5"><p>{t.caseId}: {current.id}</p><p>{t.states[current.status]}</p>
 {current.status==="draft"&&<><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void add((f.getAll("files") as File[]).filter(x=>x.size>0),String(f.get("kind")) as typeof evidenceKinds[number]);}}><label>{t.kind}<select name="kind" className={fieldClass}>{evidenceKinds.map(k=><option key={k} value={k}>{t.kinds[k]}</option>)}</select></label><label>{t.files}<input name="files" type="file" multiple required className={fieldClass}/></label><button className={buttonClass} disabled={busy}>{t.add}</button></form>
 <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void add([new Blob([String(f.get("text"))],{type:"text/plain"})],String(f.get("kind")) as typeof evidenceKinds[number]);}}><label>{t.kind}<select name="kind" className={fieldClass}>{["transcript","call_metadata"].map(k=><option key={k} value={k}>{t.kinds[k as "transcript"|"call_metadata"]}</option>)}</select></label><label>{t.text}<textarea name="text" required maxLength={100000} className={fieldClass}/></label><button className={buttonClass} disabled={busy}>{t.add}</button></form></>}
 <ul>{ownItems.map(x=><li className="my-4 break-all border-b pb-3" key={x.id}>{t.kinds[x.kind]} · {x.size} · {x.sha256}{local[x.id]&&<button className={buttonClass} onClick={()=>download(local[x.id],"evidence-"+x.id)}>{t.original}</button>}</li>)}</ul>
 <button className={buttonClass} disabled={busy||!ownItems.length} onClick={()=>void run(async()=>{const m=manifest();const hash=await manifestHash(m);download(new Blob([JSON.stringify({manifest:m,manifestHash:hash,anchor:anchorInfo()},null,2)],{type:"application/json"}),"satyacall-manifest-"+selected+".json");})}>{t.export}</button>
 <button className={buttonClass} disabled={busy||!ownItems.length||current.status==="anchored"} onClick={()=>void run(async()=>{await send("/api/evidence/"+selected+"/anchor",{});setDraft("");})}>{t.anchor}</button>
 {current.onchain_tx&&<p className="break-all">{t.transaction}: {current.onchain_tx}</p>}{current.anchored_at&&<p>{t.anchorTime}: {current.anchored_at}</p>}
 <p>{t.limitations}</p>
 {ownItems.length>0&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const m=manifest();const value=Object.fromEntries(["name","contact","incidentAt","description","suspect","amount","transactionRefs"].map(k=>[k,String(f.get(k)??"")]));setDraft(complaintDraft(value,m,await manifestHash(m),anchorInfo(),locale));});}}><h2 className="text-3xl font-bold">{t.complaint}</h2><p>{t.draftNotice}</p>{(["name","contact","incidentAt","description","suspect","amount","transactionRefs"] as const).map(k=><label className="block" key={k}>{t[k]}<textarea name={k} required={k==="description"} maxLength={k==="description"?10000:k==="suspect"||k==="transactionRefs"?2000:150} className={fieldClass}/></label>)}<button className={buttonClass} disabled={busy}>{t.generate}</button></form>}
 </section>}</div>
 {draft&&<section className="space-y-4"><div className="flex flex-wrap gap-4 print:hidden"><button className={buttonClass} onClick={()=>window.print()}>{t.print}</button><button className={buttonClass} onClick={()=>download(new Blob([draft],{type:"text/plain;charset=utf-8"}),"satyacall-complaint-draft.txt")}>{t.downloadDraft}</button></div><pre className="whitespace-pre-wrap break-words rounded border p-5 font-sans text-lg">{draft}</pre></section>}
 </main>;
}
