"use client";
import {useEffect,useState,useCallback} from "react";
import {purposes,type OfficialAction} from "../../lib/intent-schema";
import {intentMessages,verificationMessages,onboardingMessages} from "../../lib/i18n";
import {useLanguage} from "./language";
import {buttonClass,fieldClass} from "./key-panel";
export function IntentPanel({mode,institutionId}:{mode:"officer"|"issuer";institutionId:string}){
 const{locale}=useLanguage();const t=intentMessages[locale];const [actions,setActions]=useState<OfficialAction[]>([]);const [payees,setPayees]=useState<{id:string;payee:string;label:string;active:boolean;institution_id:string}[]>([]);const [busy,setBusy]=useState(false);const[error,setError]=useState(false);
 const load=useCallback(async()=>{const[a,p]=await Promise.all([fetch("/api/actions",{cache:"no-store"}),fetch("/api/payees",{cache:"no-store"})]);if(!a.ok||!p.ok)throw new Error();return {actions:(await a.json()).actions as OfficialAction[],payees:(await p.json()).payees as {id:string;payee:string;label:string;active:boolean;institution_id:string}[]};},[]);
 useEffect(()=>{let live=true;load().then(data=>{if(live){setActions(data.actions);setPayees(data.payees);}}).catch(()=>{if(live)setError(true);});return()=>{live=false;};},[load]);
 async function send(url:string,payload:unknown,method="POST"){setBusy(true);setError(false);try{const res=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!res.ok)throw new Error();const data=await load();setActions(data.actions);setPayees(data.payees);window.dispatchEvent(new Event("satyacall:actions-refresh"));}catch{setError(true);}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-xl border border-slate-400 p-5"><h2 className="text-3xl font-bold">{t.actions}</h2>{error&&<p role="alert">{verificationMessages[locale].error}</p>}
 {mode==="officer"?<form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payment=f.get("payment")==="on";const until=new Date(String(f.get("until")));if(!Number.isFinite(until.getTime())){setError(true);return;}void send("/api/actions",{purpose:f.get("purpose"),caseRef:f.get("case"),paymentAllowed:payment,payee:payment?f.get("payee"):"",amountCap:payment?f.get("cap"):"0.00",validUntil:until.toISOString()});}}>
 <h3 className="text-2xl font-bold">{t.create}</h3><label className="block">{t.purpose}<select name="purpose" className={fieldClass}>{purposes.map(p=><option key={p} value={p}>{t.purposes[p]}</option>)}</select></label>
 <label className="block">{t.caseRef}<input name="case" required maxLength={100} className={fieldClass}/></label><label className="block">{t.until}<input name="until" type="datetime-local" required className={fieldClass}/></label>
 <label className="block"><input name="payment" type="checkbox"/> {t.payment}</label><label className="block">{t.payee}<select name="payee" className={fieldClass}><option value="">—</option>{payees.filter(p=>p.active&&p.institution_id===institutionId).map(p=><option key={p.id} value={p.payee}>{p.label} · {p.payee}</option>)}</select></label>
 <label className="block">{t.cap}<input name="cap" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" defaultValue="0.00" className={fieldClass}/></label><button className={buttonClass} disabled={busy}>{t.create}</button></form>:
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("/api/payees",{institutionId,payee:f.get("payee"),label:f.get("label"),active:true,isInstitutional:true});}}><label className="block">{t.payee}<input name="payee" required maxLength={140} className={fieldClass}/></label><p>{t.payeeHint}</p><label className="block">{t.label}<input name="label" required maxLength={100} className={fieldClass}/></label><label className="block"><input type="checkbox" required/> {t.institutional}</label><button className={buttonClass} disabled={busy}>{t.savePayee}</button></form>}
 {mode==="issuer"&&payees.filter(p=>p.institution_id===institutionId&&p.active).map(p=><div key={p.id} className="flex flex-wrap gap-3"><span>{p.label} · {p.payee}</span><button className={buttonClass} disabled={busy} onClick={()=>send("/api/payees",{institutionId,payee:p.payee,label:p.label,active:false,isInstitutional:true})}>{onboardingMessages[locale].revoke}</button></div>)}
 {actions.filter(a=>a.institution_id===institutionId).map(a=><article key={a.id} className="space-y-2 border-t border-slate-400 py-4"><p className="break-all">{a.id}</p><p>{t.purposes[a.purpose]} · {a.case_ref} · {t[a.status]}</p><p>{t.until}: {a.valid_until}</p><p>{t.cap}: {a.amount_cap} · {a.payee}</p>{mode==="issuer"&&a.status!=="revoked"&&<div className="flex gap-3">{a.status==="pending"&&<button className={buttonClass} disabled={busy} onClick={()=>send(`/api/actions/${a.id}`,{operation:"approve"},"PATCH")}>{onboardingMessages[locale].approve}</button>}<button className={buttonClass} disabled={busy} onClick={()=>send(`/api/actions/${a.id}`,{operation:"revoke"},"PATCH")}>{onboardingMessages[locale].revoke}</button></div>}</article>)}
 </section>;
}
