"use client";
import {useEffect,useRef,useState} from "react";import Link from "next/link";import {z} from "zod";
import {normalizeIdentifier,identifierTypes,reportCategories,type IdentifierType} from "../../lib/normalize";
import {lookupResultSchema,publicReportSchema,txExplorerUrl,type LookupResult,type PublicReport} from "../../lib/registry-client";
import {registryMessages} from "../../lib/i18n";import {useLanguage} from "./language";import {fieldClass,buttonClass} from "./key-panel";
export function RegistryPanel(){const{locale}=useLanguage();const t=registryMessages[locale];const[value,setValue]=useState("");const[type,setType]=useState<IdentifierType>("phone");const[category,setCategory]=useState<typeof reportCategories[number]>("impersonation");const[ack,setAck]=useState(false);const[logged,setLogged]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[result,setResult]=useState<LookupResult|null>(null);const[recent,setRecent]=useState<PublicReport[]>([]);const[mine,setMine]=useState<PublicReport[]>([]);const pending=useRef<AbortController|null>(null);
 useEffect(()=>{const controller=new AbortController();let cancelled=false;async function load(){try{const r=await fetch("/api/report",{signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error?.code);if(!cancelled)setRecent(z.array(publicReportSchema).parse(d.reports));}catch{if(!cancelled)setError("SERVICE_UNAVAILABLE");}try{const r=await fetch("/api/auth/me",{signal:controller.signal});if(r.ok&&!cancelled){setLogged(true);const reports=await fetch("/api/report?mine=true",{signal:controller.signal});if(reports.ok&&!cancelled)setMine(z.array(publicReportSchema).parse((await reports.json()).reports));}}catch{/* Anonymous lookup remains available. */}}void load();return()=>{cancelled=true;controller.abort();pending.current?.abort();};},[]);
 async function refresh(signal:AbortSignal){for(const own of [false,true]){if(own&&!logged)continue;const r=await fetch(own?"/api/report?mine=true":"/api/report",{signal});const d=await r.json();if(!r.ok)throw new Error(d.error?.code);const rows=z.array(publicReportSchema).parse(d.reports);if(!signal.aborted)(own?setMine:setRecent)(rows);}}
 async function run(action:"lookup"|"report",id?:string){setError("");setMessage("");setBusy(true);const controller=new AbortController();pending.current?.abort();pending.current=controller;try{if(!id)normalizeIdentifier(value,type);const url=id?"/api/report/"+id+"/anchor":action==="report"?"/api/report":"/api/lookup?"+new URLSearchParams({value,type});const r=await fetch(url,{method:action==="lookup"?"GET":"POST",headers:action==="report"?{"Content-Type":"application/json"}:undefined,body:action==="report"?JSON.stringify(id?{}:{value,type,category,acknowledge:ack}):undefined,signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error?.code??"SERVICE_UNAVAILABLE");if(controller.signal.aborted)return;if(action==="lookup")setResult(lookupResultSchema.parse(d));else{setMessage(d.warning?"ANCHOR_PENDING":"ANCHORED");setValue("");setResult(null);await refresh(controller.signal);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error&&e.message.startsWith("INVALID")?"INVALID_IDENTIFIER":e instanceof z.ZodError?"INVALID_IDENTIFIER":e instanceof Error?e.message:"SERVICE_UNAVAILABLE");}finally{if(!controller.signal.aborted)setBusy(false);}}
 function list(rows:PublicReport[],own=false){return rows.length?<ul className="space-y-4">{rows.map(row=><li key={row.id} className="space-y-2 rounded border p-4"><p>{t.types[row.id_type]} · {t.categories[row.category as typeof reportCategories[number]]??t.categories.other}</p><p>{new Date(row.created_at).toLocaleString(locale)} · {row.anchor_status==="anchored"?t.anchored:t.pending}</p>{row.anchored_tx&&(txExplorerUrl(row.anchored_tx,row.chain_id)?<a className="block break-all underline" href={txExplorerUrl(row.anchored_tx,row.chain_id)!} target="_blank" rel="noreferrer">{t.explorer}: {row.anchored_tx}</a>:<p className="break-all">{t.local}: {row.anchored_tx}</p>)}{own&&row.anchor_status!=="anchored"&&<button className={buttonClass} disabled={busy} onClick={()=>void run("report",row.id)}>{t.retry}</button>}</li>)}</ul>:<p>{t.empty}</p>;}
 return <main className="mx-auto max-w-3xl space-y-6 px-5 py-10 text-xl"><h1 className="text-4xl font-bold">{t.title}</h1><p className="rounded border-2 border-amber-900 bg-amber-50 p-4">{t.warning}</p><p>{t.privacy}</p><label className="block">{t.type}<select className={fieldClass} value={type} disabled={busy} onChange={e=>{setType(e.target.value as IdentifierType);setResult(null);}}>{identifierTypes.map(kind=><option key={kind} value={kind}>{t.types[kind]}</option>)}</select></label><label className="block">{t.value}<input className={fieldClass} autoComplete="off" maxLength={128} disabled={busy} value={value} onChange={e=>{setValue(e.target.value);setResult(null);}}/></label><button className={buttonClass} disabled={busy||!value.trim()} onClick={()=>void run("lookup")}>{t.lookup}</button>
 {result&&<section role="status" className={"space-y-3 rounded border-4 p-5 "+(result.risk==="high"?"border-red-800":result.risk==="reported"?"border-amber-800":"border-teal-800")}><h2 className="text-3xl font-bold">{t.risks[result.risk]}</h2><p>{t.count}: {result.count} · {t.distinct}: {result.distinctReporterCount}</p><p>{t.eligible}: {result.eligibleReporterCount}</p><p>{t.minimumAge}: {result.minAccountAgeSeconds}</p><p>{t.chain}: {result.anchoredCount} / {result.chainCount??t.unavailable}</p>{result.pendingCount>0&&<p>{t.pending}: {result.pendingCount}</p>}{result.countsMatch===false&&<p>{t.mismatch}</p>}</section>}
 <section className="space-y-3 border-t pt-5"><h2 className="text-2xl font-bold">{t.report}</h2><label className="block">{t.category}<select className={fieldClass} disabled={busy} value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{reportCategories.map(kind=><option key={kind} value={kind}>{t.categories[kind]}</option>)}</select></label><label className="block"><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/> {t.acknowledge}</label>{logged?<button className={buttonClass} disabled={busy||!ack||!value.trim()} onClick={()=>void run("report")}>{t.report}</button>:<Link className="underline" href="/login">{t.login}</Link>}</section>
 {busy&&<p role="status">{t.busy}</p>}{error&&<p role="alert">{t.errors[error]??t.error}</p>}{message&&<p role="status">{message==="ANCHORED"?t.success:t.errors.ANCHOR_PENDING}</p>}
 {logged&&<section className="space-y-3"><h2 className="text-2xl font-bold">{t.mine}</h2>{list(mine,true)}</section>}<section className="space-y-3"><h2 className="text-2xl font-bold">{t.recent}</h2>{list(recent)}</section></main>;
}
