"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {z} from "zod";import {latestRisk} from "../../lib/analyzer-state";import {guardReasons,secondsRemaining} from "../../lib/upi-guard";import {commonMessages,assistMessages} from "../../lib/i18n";import {useLanguage} from "./language";import {buttonClass,fieldClass} from "./key-panel";
const sessionSchema=z.object({id:z.string().uuid(),coolingUntil:z.string(),serverNow:z.string(),expiresAt:z.string(),threshold:z.string(),amount:z.string(),reasons:z.array(z.enum(guardReasons)),alertId:z.string().uuid().nullable(),token:z.string().regex(/^[0-9a-f]{64}$/)});
const storedSchema=z.object({session:sessionSchema,offset:z.number(),payee:z.string().max(121),alert:z.object({status:z.enum(["sent","failed","pending"]),mode:z.enum(["in_app","webhook"])}).nullable()});
type Session=z.infer<typeof sessionSchema>;type Alert=z.infer<typeof storedSchema>["alert"];
export function UpiGuard(){const{locale}=useLanguage();const t=assistMessages[locale];const[session,setSession]=useState<Session|null>(null);const[payee,setPayee]=useState("");const[alert,setAlert]=useState<Alert>(null);const[offset,setOffset]=useState(0);const[now,setNow]=useState(()=>Date.now());const[risk,setRisk]=useState<"LOW"|"MEDIUM"|"HIGH">("LOW");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[choice,setChoice]=useState<"cancel"|"continue"|null>(null);const[count,setCount]=useState<number|null>(null);
 useEffect(()=>{const update=()=>{setNow(Date.now());setRisk(latestRisk());};const timer=setInterval(update,1000);window.addEventListener("satyacall:analysis",update);const restore=()=>{try{const d=storedSchema.parse(JSON.parse(sessionStorage.getItem("satyacall:upi-demo")??"null"));if(Date.parse(d.session.expiresAt)>Date.now()+d.offset){setSession(d.session);setPayee(d.payee);setOffset(d.offset);setAlert(d.alert);}else sessionStorage.removeItem("satyacall:upi-demo");}catch{/* No pending demo session. */}};queueMicrotask(()=>{update();restore();});return()=>{clearInterval(timer);window.removeEventListener("satyacall:analysis",update);};},[]);
 useEffect(()=>{if(session&&Date.parse(session.expiresAt)<=now+offset){try{sessionStorage.removeItem("satyacall:upi-demo");}catch{/* Optional storage. */}}},[session,now,offset]);
 async function post(url:string,value:unknown){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const d=await r.json();if(!r.ok)throw new Error(d.error?.code);return d;}
 async function begin(f:FormData){setBusy(true);setError("");setChoice(null);try{const d=await post("/api/upi-guard",{payee:f.get("payee"),amount:f.get("amount"),latestRisk:latestRisk()});const s=sessionSchema.parse(d.session);const delta=Date.parse(s.serverNow)-Date.now();const a=storedSchema.shape.alert.parse(d.alert);setSession(s);setPayee(String(f.get("payee")).trim().toLowerCase());setOffset(delta);setAlert(a);setCount(d.registryCount);setNow(Date.now());try{sessionStorage.setItem("satyacall:upi-demo",JSON.stringify({session:s,offset:delta,payee:String(f.get("payee")).trim().toLowerCase(),alert:a}));}catch{/* Server log still exists. */}}catch(e){setError(e instanceof Error?e.message:"SERVICE_UNAVAILABLE");}finally{setBusy(false);}}
 async function choose(value:"cancel"|"continue"){if(!session)return;setBusy(true);setError("");try{const d=await post("/api/upi-guard/choice",{sessionId:session.id,token:session.token,choice:value});setChoice(z.enum(["cancel","continue"]).parse(d.choice));try{sessionStorage.removeItem("satyacall:upi-demo");}catch{/* Optional session restore. */}}catch(e){setError(e instanceof Error?e.message:"SERVICE_UNAVAILABLE");}finally{setBusy(false);}}
 const remaining=session?secondsRemaining(session.coolingUntil,now+offset):0;const expired=session?Date.parse(session.expiresAt)<=now+offset:false;
 return <main className="mx-auto max-w-3xl space-y-6 px-5 py-10 text-xl"><h1 className="text-4xl font-bold">{t.upi}</h1><p className="rounded border-4 border-amber-800 bg-amber-50 p-5 font-bold">{t.demo}</p><p>{t.guardPrivacy}</p><p>{t.latest}: {t.risks[risk]}</p><Link className="underline" href="/analyze">{t.analyze}</Link>
 {!session&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void begin(new FormData(e.currentTarget));}}><label className="block">{t.payee}<input name="payee" required maxLength={121} placeholder="synthetic@bank" className={fieldClass}/></label><label className="block">{t.amount}<input name="amount" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" className={fieldClass}/></label><button className={buttonClass} disabled={busy}>{t.simulate}</button></form>}
 {error&&<p role="alert">{t.errors[error]??t.error}</p>}{busy&&<p>{t.pending}</p>}
 {session&&<section className="space-y-5 rounded border-2 p-5"><p className="break-all">{t.payee}: {payee}</p><p>{t.amount}: {session.amount} INR</p><p>{t.threshold}: {session.threshold} INR</p>{count!==null&&<p>{t.registryCount}: {count}</p>}{session.reasons.length>0?<><h2 className="text-3xl font-bold">{t.cooling}</h2><ul>{session.reasons.map(x=><li key={x}>{t.guardReasons[x]}</li>)}</ul><p role="timer" className="text-5xl font-bold">{remaining} {commonMessages[locale].seconds}</p><p className="font-bold">{t.pressure}</p><p>{t.prompt}</p></>:<p>{t.noTriggers}</p>}
 {alert&&<p role="status">{alert.status==="failed"?t.alertFailed:alert.mode==="webhook"?t.alertWebhook:t.alertLocal}</p>}
 {expired&&<><p>{t.expired}</p><button className={buttonClass} onClick={()=>{setSession(null);setAlert(null);setCount(null);try{sessionStorage.removeItem("satyacall:upi-demo");}catch{/* Optional storage. */}}}>{t.again}</button></>}{choice?<><p className="text-3xl font-bold">{choice==="cancel"?t.cancelled:t.continued}</p><p>{t.logged}</p><button className={buttonClass} onClick={()=>{setSession(null);setChoice(null);setAlert(null);setCount(null);}}>{t.again}</button></>:<div className="flex flex-wrap gap-4"><button className={buttonClass} disabled={busy||expired} onClick={()=>choose("cancel")}>{t.cancel}</button><button className={buttonClass} disabled={busy||expired||remaining>0} onClick={()=>choose("continue")}>{t.continue}</button></div>}
 </section>}<Link className="underline" href="/guardian">{t.guardian}</Link></main>;
}

